\set queryname dblp_acyclic_214_00
-- Result size: 1958328
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp17:s -> dblp7:s;dblp7:s -> dblp21:s;dblp21:s -> dblp20:s;dblp20:s -> dblp6:s;dblp6:s -> dblp2:s;dblp2:d -> dblp14:s;dblp14:d -> dblp5:s;}
--                +--------+----+----+-------+----+---+
--                | dblp14 |  s |  d | dblp5 |  s | d |
--                +--------+----+----+-------+----+---+
--                            |    |            |
--   +------------------------+    +------------+
--   |
--   |  +--------+---------+----+
--   |  | dblp17 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp7  |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp21 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp20 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp6  |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp2  |    s    |  d |
--   |  +--------+---------+----+
--   |                        |
--   +------------------------+
select count(*) from dblp17, dblp7, dblp21, dblp20, dblp6, dblp2, dblp14, dblp5 where dblp17.s = dblp7.s and dblp7.s = dblp21.s and dblp21.s = dblp20.s and dblp20.s = dblp6.s and dblp6.s = dblp2.s and dblp2.d = dblp14.s and dblp14.d = dblp5.s;
\set queryname dblp_acyclic_214_01
-- Result size: 1155328
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp10 [label="dblp10|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp23:s -> dblp10:s;dblp10:s -> dblp1:s;dblp1:s -> dblp22:s;dblp22:s -> dblp18:s;dblp18:s -> dblp9:s;dblp9:d -> dblp8:s;dblp8:d -> dblp2:s;}
--                    +--------+----+----+
--                    | dblp9  |  s |  d |
--                    +--------+----+----+
--                                |    |
--                                |    +----+
--                                |         |
--                    +--------+----+----+  |
--                    | dblp18 |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                |         |
--                                |         |
--                    +--------+----+----+  |
--                    | dblp22 |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                |         |
--                                |         |
--                    +--------+----+----+  |
--                    | dblp1  |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                +----+    |
--                                     |    |
--          +--------+---------+----+  |    |
--          | dblp23 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      |              |    |
--                      |              |    |
--          +--------+---------+----+  |    |
--          | dblp10 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      +--------------+    |
--                                          |
--                                          |
--            +-----------------------------+
--            |
-- +-------+---------+---------+
-- | dblp8 |    s    |    d    |
-- +-------+---------+---------+
--                      |
--                      |
--                      |
--          +--------+---------+----+
--          | dblp2  |    s    |  d |
--          +--------+---------+----+
select count(*) from dblp23, dblp10, dblp1, dblp22, dblp18, dblp9, dblp8, dblp2 where dblp23.s = dblp10.s and dblp10.s = dblp1.s and dblp1.s = dblp22.s and dblp22.s = dblp18.s and dblp18.s = dblp9.s and dblp9.d = dblp8.s and dblp8.d = dblp2.s;
\set queryname dblp_acyclic_214_02
-- Result size: 11879912
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp6:s -> dblp5:s;dblp5:s -> dblp23:s;dblp23:s -> dblp25:s;dblp25:s -> dblp1:s;dblp1:s -> dblp21:s;dblp21:d -> dblp9:s;dblp9:d -> dblp7:s;}
--           +--------+----+----+-------+----+----+-------+----+---+
--           | dblp21 |  s |  d | dblp9 |  s |  d | dblp7 |  s | d |
--           +--------+----+----+-------+----+----+-------+----+---+
--                       |    |            |    |            |
--                       |    +------------+    +------------+
--                       |
--           +--------+----+----+
--           | dblp1  |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp6  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp5  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp23 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp25 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             +--------------+
select count(*) from dblp6, dblp5, dblp23, dblp25, dblp1, dblp21, dblp9, dblp7 where dblp6.s = dblp5.s and dblp5.s = dblp23.s and dblp23.s = dblp25.s and dblp25.s = dblp1.s and dblp1.s = dblp21.s and dblp21.d = dblp9.s and dblp9.d = dblp7.s;
\set queryname dblp_acyclic_214_03
-- Result size: 19770560
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp20:s -> dblp18:s;dblp18:s -> dblp21:s;dblp21:s -> dblp25:s;dblp25:s -> dblp17:s;dblp17:s -> dblp8:s;dblp8:d -> dblp9:s;dblp9:d -> dblp12:s;}
--           +--------+----+----+
--           | dblp12 |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp20 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp18 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp21 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp25 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp17 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp8  |    s    |  d |  |
-- +--------+---------+----+  |
--                       |    |
--                       |    |
--                       |    |
--           +--------+----+----+
--           | dblp9  |  s |  d |
--           +--------+----+----+
select count(*) from dblp20, dblp18, dblp21, dblp25, dblp17, dblp8, dblp9, dblp12 where dblp20.s = dblp18.s and dblp18.s = dblp21.s and dblp21.s = dblp25.s and dblp25.s = dblp17.s and dblp17.s = dblp8.s and dblp8.d = dblp9.s and dblp9.d = dblp12.s;
\set queryname dblp_acyclic_214_04
-- Result size: 634053
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp16:s -> dblp7:s;dblp7:s -> dblp8:s;dblp8:s -> dblp2:s;dblp2:s -> dblp17:s;dblp17:s -> dblp1:s;dblp1:d -> dblp26:s;dblp26:d -> dblp21:s;}
--                           +-------------+
--                           |             |
--           +-------+----+----+--------+---------+----+
--           | dblp1 |  s |  d | dblp26 |    s    |  d |
--           +-------+----+----+--------+---------+----+
--                      |                            |
--                      +----+                       |
--                           |                       |
-- +--------+--------+----+  |           +--------+----+---+
-- | dblp16 |    s   |  d |  |           | dblp21 |  s | d |
-- +--------+--------+----+  |           +--------+----+---+
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp7  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp8  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp2  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp17 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             +-------------+
select count(*) from dblp16, dblp7, dblp8, dblp2, dblp17, dblp1, dblp26, dblp21 where dblp16.s = dblp7.s and dblp7.s = dblp8.s and dblp8.s = dblp2.s and dblp2.s = dblp17.s and dblp17.s = dblp1.s and dblp1.d = dblp26.s and dblp26.d = dblp21.s;
\set queryname dblp_acyclic_214_05
-- Result size: 3646673
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp8:s -> dblp14:s;dblp14:s -> dblp21:s;dblp21:s -> dblp2:s;dblp2:s -> dblp16:s;dblp16:s -> dblp19:s;dblp19:d -> dblp17:s;dblp17:d -> dblp1:s;}
--             +------------------+
--             |                  |
-- +--------+--------+----+       |
-- | dblp17 |    s   |  d |       |
-- +--------+--------+----+       |
--                      |         |
--                      |         |
--                      |         |
--           +-------+----+----+  |
--           | dblp1 |  s |  d |  |
--           +-------+----+----+  |
-- +--------+--------+----+       |
-- | dblp8  |    s   |  d |       |
-- +--------+--------+----+       |
--             |                  |
--             |                  |
--             |                  |
-- +--------+--------+----+       |
-- | dblp14 |    s   |  d |       |
-- +--------+--------+----+       |
--             |                  |
--             |                  |
--             |                  |
-- +--------+--------+----+       |
-- | dblp21 |    s   |  d |       |
-- +--------+--------+----+       |
--             |                  |
--             |                  |
--             |                  |
-- +--------+--------+----+       |
-- | dblp2  |    s   |  d |       |
-- +--------+--------+----+       |
--             |                  |
--             |                  |
--             |                  |
-- +--------+--------+----+       |
-- | dblp16 |    s   |  d |       |
-- +--------+--------+----+       |
--             |                  |
--             |                  |
--             |                  |
-- +--------+--------+----+       |
-- | dblp19 |    s   |  d | ------+
-- +--------+--------+----+
select count(*) from dblp8, dblp14, dblp21, dblp2, dblp16, dblp19, dblp17, dblp1 where dblp8.s = dblp14.s and dblp14.s = dblp21.s and dblp21.s = dblp2.s and dblp2.s = dblp16.s and dblp16.s = dblp19.s and dblp19.d = dblp17.s and dblp17.d = dblp1.s;
\set queryname dblp_acyclic_214_06
-- Result size: 9707488
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp14:s -> dblp20:s;dblp20:s -> dblp24:s;dblp24:s -> dblp5:s;dblp5:s -> dblp7:s;dblp7:s -> dblp8:s;dblp8:d -> dblp9:s;dblp9:d -> dblp12:s;}
--           +--------+----+----+
--           | dblp12 |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp14 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp20 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp24 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp5  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp7  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp8  |    s    |  d |  |
-- +--------+---------+----+  |
--                       |    |
--                       |    |
--                       |    |
--           +--------+----+----+
--           | dblp9  |  s |  d |
--           +--------+----+----+
select count(*) from dblp14, dblp20, dblp24, dblp5, dblp7, dblp8, dblp9, dblp12 where dblp14.s = dblp20.s and dblp20.s = dblp24.s and dblp24.s = dblp5.s and dblp5.s = dblp7.s and dblp7.s = dblp8.s and dblp8.d = dblp9.s and dblp9.d = dblp12.s;
\set queryname dblp_acyclic_214_07
-- Result size: 289746
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp19:s -> dblp25:s;dblp25:s -> dblp16:s;dblp16:s -> dblp6:s;dblp6:s -> dblp17:s;dblp17:s -> dblp21:s;dblp21:d -> dblp5:s;dblp5:d -> dblp24:s;}
--           +--------+----+----+-------+----+----+--------+----+---+
--           | dblp21 |  s |  d | dblp5 |  s |  d | dblp24 |  s | d |
--           +--------+----+----+-------+----+----+--------+----+---+
--                       |    |            |    |             |
--                       |    +------------+    +-------------+
--                       |
--           +--------+----+----+
--           | dblp17 |  s |  d |
--           +--------+----+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp6  |  s |  d |
--           +--------+----+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp16 |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp19 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp25 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             +--------------+
select count(*) from dblp19, dblp25, dblp16, dblp6, dblp17, dblp21, dblp5, dblp24 where dblp19.s = dblp25.s and dblp25.s = dblp16.s and dblp16.s = dblp6.s and dblp6.s = dblp17.s and dblp17.s = dblp21.s and dblp21.d = dblp5.s and dblp5.d = dblp24.s;
\set queryname dblp_acyclic_214_08
-- Result size: 943947
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp1:s -> dblp6:s;dblp6:s -> dblp7:s;dblp7:s -> dblp9:s;dblp9:s -> dblp17:s;dblp17:s -> dblp5:s;dblp5:d -> dblp8:s;dblp8:d -> dblp18:s;}
-- +--------+--------+---------+
-- | dblp1  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp6  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp7  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp9  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp17 |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp5  |    s   |    d    |
-- +--------+--------+---------+
--                      |
--                      |
--                      |
--           +-------+---------+----+
--           | dblp8 |    s    |  d |
--           +-------+---------+----+
--                                |
--                                |
--                                |
--                    +--------+----+---+
--                    | dblp18 |  s | d |
--                    +--------+----+---+
select count(*) from dblp1, dblp6, dblp7, dblp9, dblp17, dblp5, dblp8, dblp18 where dblp1.s = dblp6.s and dblp6.s = dblp7.s and dblp7.s = dblp9.s and dblp9.s = dblp17.s and dblp17.s = dblp5.s and dblp5.d = dblp8.s and dblp8.d = dblp18.s;
\set queryname dblp_acyclic_214_09
-- Result size: 14268660
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp6:s -> dblp17:s;dblp17:s -> dblp9:s;dblp9:s -> dblp23:s;dblp23:s -> dblp1:s;dblp1:s -> dblp2:s;dblp2:d -> dblp25:s;dblp25:d -> dblp21:s;}
--           +-------+----+----+--------+----+----+--------+----+---+
--           | dblp2 |  s |  d | dblp25 |  s |  d | dblp21 |  s | d |
--           +-------+----+----+--------+----+----+--------+----+---+
--                      |    |             |    |             |
--                      |    +-------------+    +-------------+
--                      |
--           +-------+----+----+
--           | dblp1 |  s |  d |
--           +-------+----+----+
--                      |
--                      +----+
--                           |
-- +--------+--------+----+  |
-- | dblp6  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp17 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp9  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp23 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             +-------------+
select count(*) from dblp6, dblp17, dblp9, dblp23, dblp1, dblp2, dblp25, dblp21 where dblp6.s = dblp17.s and dblp17.s = dblp9.s and dblp9.s = dblp23.s and dblp23.s = dblp1.s and dblp1.s = dblp2.s and dblp2.d = dblp25.s and dblp25.d = dblp21.s;
\set queryname dblp_acyclic_214_10
-- Result size: 1137004
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp4 [label="dblp4|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp18:s -> dblp24:s;dblp24:s -> dblp23:s;dblp23:s -> dblp4:s;dblp4:s -> dblp22:s;dblp22:s -> dblp5:s;dblp5:d -> dblp8:s;dblp8:d -> dblp1:s;}
--           +-------+----+----+
--           | dblp1 |  s |  d |
--           +-------+----+----+
--                      |
--                      +----+
--                           |
-- +--------+--------+----+  |
-- | dblp18 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp24 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp23 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp4  |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp22 |    s   |  d |  |
-- +--------+--------+----+  |
--             |             |
--             |             |
--             |             |
-- +--------+--------+----+  |
-- | dblp5  |    s   |  d |  |
-- +--------+--------+----+  |
--                      |    |
--                      |    |
--                      |    |
--           +-------+----+----+
--           | dblp8 |  s |  d |
--           +-------+----+----+
select count(*) from dblp18, dblp24, dblp23, dblp4, dblp22, dblp5, dblp8, dblp1 where dblp18.s = dblp24.s and dblp24.s = dblp23.s and dblp23.s = dblp4.s and dblp4.s = dblp22.s and dblp22.s = dblp5.s and dblp5.d = dblp8.s and dblp8.d = dblp1.s;
\set queryname dblp_acyclic_214_11
-- Result size: 526428
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp22:s -> dblp7:s;dblp7:s -> dblp21:s;dblp21:s -> dblp19:s;dblp19:s -> dblp6:s;dblp6:s -> dblp5:s;dblp5:d -> dblp8:s;dblp8:d -> dblp18:s;}
--           +--------+----+----+
--           | dblp18 |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp22 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp7  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp21 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp19 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp6  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp5  |    s    |  d |  |
-- +--------+---------+----+  |
--                       |    |
--                       |    |
--                       |    |
--           +--------+----+----+
--           | dblp8  |  s |  d |
--           +--------+----+----+
select count(*) from dblp22, dblp7, dblp21, dblp19, dblp6, dblp5, dblp8, dblp18 where dblp22.s = dblp7.s and dblp7.s = dblp21.s and dblp21.s = dblp19.s and dblp19.s = dblp6.s and dblp6.s = dblp5.s and dblp5.d = dblp8.s and dblp8.d = dblp18.s;
\set queryname dblp_acyclic_214_12
-- Result size: 1959947
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp8:s -> dblp1:s;dblp1:s -> dblp17:s;dblp17:s -> dblp6:s;dblp6:s -> dblp18:s;dblp18:s -> dblp25:s;dblp25:d -> dblp26:s;dblp26:d -> dblp5:s;}
-- +--------+----+----+--------+----+----+-------+----+---+
-- | dblp25 |  s |  d | dblp26 |  s |  d | dblp5 |  s | d |
-- +--------+----+----+--------+----+----+-------+----+---+
--             |    |             |    |            |
--             |    +-------------+    +------------+
--             |
-- +--------+----+----+
-- | dblp18 |  s |  d |
-- +--------+----+----+
--             |
--             |
--             |
-- +--------+----+----+
-- | dblp6  |  s |  d |
-- +--------+----+----+
--             |
--             |
--             |
-- +--------+----+----+
-- | dblp17 |  s |  d |
-- +--------+----+----+
--             |
--             |
--             |
-- +--------+----+----+
-- | dblp1  |  s |  d |
-- +--------+----+----+
--             |
--             |
--             |
-- +--------+----+----+
-- | dblp8  |  s |  d |
-- +--------+----+----+
select count(*) from dblp8, dblp1, dblp17, dblp6, dblp18, dblp25, dblp26, dblp5 where dblp8.s = dblp1.s and dblp1.s = dblp17.s and dblp17.s = dblp6.s and dblp6.s = dblp18.s and dblp18.s = dblp25.s and dblp25.d = dblp26.s and dblp26.d = dblp5.s;
\set queryname dblp_acyclic_214_13
-- Result size: 6744529
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp24:s -> dblp7:s;dblp7:s -> dblp25:s;dblp25:s -> dblp1:s;dblp1:s -> dblp18:s;dblp18:s -> dblp21:s;dblp21:d -> dblp2:s;dblp2:d -> dblp8:s;}
--                    +--------+----+----+
--                    | dblp21 |  s |  d |
--                    +--------+----+----+
--                                |    |
--                                |    +----+
--                                |         |
--                    +--------+----+----+  |
--                    | dblp18 |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                |         |
--                                |         |
--                    +--------+----+----+  |
--                    | dblp1  |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                +----+    |
--                                     |    |
--          +--------+---------+----+  |    |
--          | dblp24 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      |              |    |
--                      |              |    |
--          +--------+---------+----+  |    |
--          | dblp7  |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      |              |    |
--                      |              |    |
--          +--------+---------+----+  |    |
--          | dblp25 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      +--------------+    |
--                                          |
--                                          |
--            +-----------------------------+
--            |
-- +-------+---------+---------+
-- | dblp2 |    s    |    d    |
-- +-------+---------+---------+
--                      |
--                      |
--                      |
--          +--------+---------+----+
--          | dblp8  |    s    |  d |
--          +--------+---------+----+
select count(*) from dblp24, dblp7, dblp25, dblp1, dblp18, dblp21, dblp2, dblp8 where dblp24.s = dblp7.s and dblp7.s = dblp25.s and dblp25.s = dblp1.s and dblp1.s = dblp18.s and dblp18.s = dblp21.s and dblp21.d = dblp2.s and dblp2.d = dblp8.s;
\set queryname dblp_acyclic_214_14
-- Result size: 3793642
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp7:s -> dblp1:s;dblp1:s -> dblp24:s;dblp24:s -> dblp6:s;dblp6:s -> dblp21:s;dblp21:s -> dblp9:s;dblp9:d -> dblp19:s;dblp19:d -> dblp20:s;}
--             +------------------------+
--             |                        |
--             |       +--------+----+----+
--             |       | dblp9  |  s |  d |
--             |       +--------+----+----+
--             |                   |
--             |                   |
--             |                   |
--             |       +--------+----+----+
--             |       | dblp21 |  s |  d |
--             |       +--------+----+----+
--             |                   |
--             |                   |
--             |                   |
--             |       +--------+----+----+
--             |       | dblp6  |  s |  d |
--             |       +--------+----+----+
--             |                   |
--             |                   |
--             |                   |
--             |       +--------+----+----+
--             |       | dblp24 |  s |  d |
--             |       +--------+----+----+
--             |                   |
--             |                   |
--             |                   |
--             |       +--------+----+----+
--             |       | dblp1  |  s |  d |
--             |       +--------+----+----+
--             |                   |
--             |                   |
--             |                   |
--             |       +--------+----+----+
--             |       | dblp7  |  s |  d |
--             |       +--------+----+----+
--             |
--             |
--             |
-- +--------+---------+---------+
-- | dblp19 |    s    |    d    |
-- +--------+---------+---------+
--                       |
--                       |
--                       |
--           +--------+---------+----+
--           | dblp20 |    s    |  d |
--           +--------+---------+----+
select count(*) from dblp7, dblp1, dblp24, dblp6, dblp21, dblp9, dblp19, dblp20 where dblp7.s = dblp1.s and dblp1.s = dblp24.s and dblp24.s = dblp6.s and dblp6.s = dblp21.s and dblp21.s = dblp9.s and dblp9.d = dblp19.s and dblp19.d = dblp20.s;
\set queryname dblp_acyclic_214_15
-- Result size: 5406852
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp8:s -> dblp24:s;dblp24:s -> dblp5:s;dblp5:s -> dblp20:s;dblp20:s -> dblp7:s;dblp7:s -> dblp2:s;dblp2:d -> dblp19:s;dblp19:d -> dblp23:s;}
--                +--------+----+----+--------+----+---+
--                | dblp19 |  s |  d | dblp23 |  s | d |
--                +--------+----+----+--------+----+---+
--                            |    |             |
--   +------------------------+    +-------------+
--   |
--   |  +--------+---------+----+
--   |  | dblp8  |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp24 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp5  |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp20 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp7  |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp2  |    s    |  d |
--   |  +--------+---------+----+
--   |                        |
--   +------------------------+
select count(*) from dblp8, dblp24, dblp5, dblp20, dblp7, dblp2, dblp19, dblp23 where dblp8.s = dblp24.s and dblp24.s = dblp5.s and dblp5.s = dblp20.s and dblp20.s = dblp7.s and dblp7.s = dblp2.s and dblp2.d = dblp19.s and dblp19.d = dblp23.s;
\set queryname dblp_acyclic_214_16
-- Result size: 21140276
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp20:s -> dblp23:s;dblp23:s -> dblp17:s;dblp17:s -> dblp2:s;dblp2:s -> dblp6:s;dblp6:s -> dblp9:s;dblp9:d -> dblp8:s;dblp8:d -> dblp25:s;}
--                    +--------+----+----+
--                    | dblp9  |  s |  d |
--                    +--------+----+----+
--                                |    |
--                                |    +----+
--                                |         |
--                    +--------+----+----+  |
--                    | dblp6  |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                |         |
--                                |         |
--                    +--------+----+----+  |
--                    | dblp2  |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                |         |
--                                |         |
--                    +--------+----+----+  |
--                    | dblp17 |  s |  d |  |
--                    +--------+----+----+  |
--                                |         |
--                                +----+    |
--                                     |    |
--          +--------+---------+----+  |    |
--          | dblp20 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      |              |    |
--                      |              |    |
--          +--------+---------+----+  |    |
--          | dblp23 |    s    |  d |  |    |
--          +--------+---------+----+  |    |
--                      |              |    |
--                      +--------------+    |
--                                          |
--                                          |
--            +-----------------------------+
--            |
-- +-------+---------+---------+
-- | dblp8 |    s    |    d    |
-- +-------+---------+---------+
--                      |
--                      |
--                      |
--          +--------+---------+----+
--          | dblp25 |    s    |  d |
--          +--------+---------+----+
select count(*) from dblp20, dblp23, dblp17, dblp2, dblp6, dblp9, dblp8, dblp25 where dblp20.s = dblp23.s and dblp23.s = dblp17.s and dblp17.s = dblp2.s and dblp2.s = dblp6.s and dblp6.s = dblp9.s and dblp9.d = dblp8.s and dblp8.d = dblp25.s;
\set queryname dblp_acyclic_214_17
-- Result size: 2514587
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp8:s -> dblp7:s;dblp7:s -> dblp24:s;dblp24:s -> dblp17:s;dblp17:s -> dblp9:s;dblp9:s -> dblp18:s;dblp18:d -> dblp5:s;dblp5:d -> dblp22:s;}
--           +--------+----+----+-------+----+----+--------+----+---+
--           | dblp18 |  s |  d | dblp5 |  s |  d | dblp22 |  s | d |
--           +--------+----+----+-------+----+----+--------+----+---+
--                       |    |            |    |             |
--                       |    +------------+    +-------------+
--                       |
--           +--------+----+----+
--           | dblp9  |  s |  d |
--           +--------+----+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp17 |  s |  d |
--           +--------+----+----+
--                       |
--                       +----+
--                            |
-- +--------+---------+----+  |
-- | dblp8  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp7  |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             |              |
--             |              |
-- +--------+---------+----+  |
-- | dblp24 |    s    |  d |  |
-- +--------+---------+----+  |
--             |              |
--             +--------------+
select count(*) from dblp8, dblp7, dblp24, dblp17, dblp9, dblp18, dblp5, dblp22 where dblp8.s = dblp7.s and dblp7.s = dblp24.s and dblp24.s = dblp17.s and dblp17.s = dblp9.s and dblp9.s = dblp18.s and dblp18.d = dblp5.s and dblp5.d = dblp22.s;
\set queryname dblp_acyclic_214_18
-- Result size: 1803960
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp14:s -> dblp25:s;dblp25:s -> dblp7:s;dblp7:s -> dblp5:s;dblp5:s -> dblp16:s;dblp16:s -> dblp19:s;dblp19:d -> dblp9:s;dblp9:d -> dblp18:s;}
-- +--------+--------+---------+
-- | dblp14 |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp25 |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp7  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp5  |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp16 |    s   |    d    |
-- +--------+--------+---------+
--             |
--             |
--             |
-- +--------+--------+---------+
-- | dblp19 |    s   |    d    |
-- +--------+--------+---------+
--                      |
--                      |
--                      |
--           +-------+---------+----+
--           | dblp9 |    s    |  d |
--           +-------+---------+----+
--                                |
--                                |
--                                |
--                    +--------+----+---+
--                    | dblp18 |  s | d |
--                    +--------+----+---+
select count(*) from dblp14, dblp25, dblp7, dblp5, dblp16, dblp19, dblp9, dblp18 where dblp14.s = dblp25.s and dblp25.s = dblp7.s and dblp7.s = dblp5.s and dblp5.s = dblp16.s and dblp16.s = dblp19.s and dblp19.d = dblp9.s and dblp9.d = dblp18.s;
\set queryname dblp_acyclic_214_19
-- Result size: 5869276
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp21:s -> dblp1:s;dblp1:s -> dblp5:s;dblp5:s -> dblp17:s;dblp17:s -> dblp6:s;dblp6:s -> dblp9:s;dblp9:d -> dblp8:s;dblp8:d -> dblp22:s;}
--            +------------------------+
--            |                        |
--            |       +--------+----+----+
--            |       | dblp9  |  s |  d |
--            |       +--------+----+----+
--            |                   |
--            |                   |
--            |                   |
--            |       +--------+----+----+
--            |       | dblp6  |  s |  d |
--            |       +--------+----+----+
--            |                   |
--            |                   |
--            |                   |
--            |       +--------+----+----+
--            |       | dblp17 |  s |  d |
--            |       +--------+----+----+
--            |                   |
--            |                   |
--            |                   |
--            |       +--------+----+----+
--            |       | dblp5  |  s |  d |
--            |       +--------+----+----+
--            |                   |
--            |                   |
--            |                   |
--            |       +--------+----+----+
--            |       | dblp1  |  s |  d |
--            |       +--------+----+----+
--            |                   |
--            |                   |
--            |                   |
--            |       +--------+----+----+
--            |       | dblp21 |  s |  d |
--            |       +--------+----+----+
--            |
--            |
--            |
-- +-------+---------+---------+
-- | dblp8 |    s    |    d    |
-- +-------+---------+---------+
--                      |
--                      |
--                      |
--          +--------+---------+----+
--          | dblp22 |    s    |  d |
--          +--------+---------+----+
select count(*) from dblp21, dblp1, dblp5, dblp17, dblp6, dblp9, dblp8, dblp22 where dblp21.s = dblp1.s and dblp1.s = dblp5.s and dblp5.s = dblp17.s and dblp17.s = dblp6.s and dblp6.s = dblp9.s and dblp9.d = dblp8.s and dblp8.d = dblp22.s;
