\set queryname dblp_acyclic_211_00
-- Result size: 415023989
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2:s -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp8:s;dblp8:d -> dblp21:s;}
--                                   +--------+----+----+
--                                   | dblp22 |  s |  d | -+
--                                   +--------+----+----+  |
--                                               |         |
--                                               |         |
--                                               |         |
--          +--------+----+---------+---------+----+----+  |
--          | dblp21 |  s |    d    |  dblp1  |  s |  d |  |
--          +--------+----+---------+---------+----+----+  |
--                      |                             |    |
--                      |                             |    |
--                      |                             |    |
-- +-------+---------+----+          +--------+----+----+  |
-- | dblp8 |    s    |  d |          | dblp25 |  s |  d |  |
-- +-------+---------+----+          +--------+----+----+  |
--            |                                  |         |
--            +----------------------------------+    +----+
--                                                    |
--                         +--------+---------+----+  |
--                         | dblp2  |    s    |  d |  |
--                         +--------+---------+----+  |
--                                     |              |
--                                     |              |
--                                     |              |
--                         +--------+---------+----+  |
--                         | dblp24 |    s    |  d | -+
--                         +--------+---------+----+
select count(*) from dblp2, dblp24, dblp22, dblp1, dblp25, dblp8, dblp21 where dblp2.s = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp8.s and dblp8.d = dblp21.s;
--\set queryname dblp_acyclic_211_01
-- Result size: 8443689125
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp2:s -> dblp19:s;dblp19:d -> dblp16:d;dblp16:s -> dblp1:s;dblp1:d -> dblp12:d;dblp12:s -> dblp5:s;dblp5:d -> dblp8:s;}
-- +--------+--------+----+
-- | dblp2  |    s   |  d |
-- +--------+--------+----+
--             |
--             |
--             |
-- +--------+--------+----+
-- | dblp19 |    s   |  d |
-- +--------+--------+----+
--                      |
--                      |
--                      |
-- +--------+--------+----+
-- | dblp16 |    s   |  d |
-- +--------+--------+----+
--             |
--             |
--             |
-- +--------+--------+----+
-- | dblp1  |    s   |  d |
-- +--------+--------+----+
--                      |
--                      |
--                      |
-- +--------+--------+----+
-- | dblp12 |    s   |  d |
-- +--------+--------+----+
--             |
--             |
--             |
-- +--------+--------+----+
-- | dblp5  |    s   |  d |
-- +--------+--------+----+
--                      |
--                      |
--                      |
--           +-------+----+---+
--           | dblp8 |  s | d |
--           +-------+----+---+
--select count(*) from dblp2, dblp19, dblp16, dblp1, dblp12, dblp5, dblp8 where dblp2.s = dblp19.s and dblp19.d = dblp16.d and dblp16.s = dblp1.s and dblp1.d = dblp12.d and dblp12.s = dblp5.s and dblp5.d = dblp8.s;
\set queryname dblp_acyclic_211_02
-- Result size: 422529
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp3 [label="dblp3|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp18:s -> dblp22:s;dblp22:d -> dblp24:d;dblp24:s -> dblp1:s;dblp1:d -> dblp12:d;dblp12:s -> dblp3:s;dblp3:d -> dblp5:s;}
--                +--------+----+----+
--                | dblp1  |  s |  d |
--                +--------+----+----+
--                            |    |
--   +------------------------+    |
--   |                             |
--   |            +--------+----+----+
--   |            | dblp12 |  s |  d |
--   |            +--------+----+----+
--   |                        |
--   |                        |
--   |                        |
--   |            +--------+----+----+-------+----+---+
--   |            | dblp3  |  s |  d | dblp5 |  s | d |
--   |            +--------+----+----+-------+----+---+
--   |                             |            |
--   |                             +------------+
--   |
--   |  +--------+---------+----+
--   |  | dblp18 |    s    |  d |
--   |  +--------+---------+----+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+----+
--   |  | dblp22 |    s    |  d |
--   |  +--------+---------+----+
--   |                        |
--   +--------------+         |
--                  |         |
--      +--------+---------+----+
--      | dblp24 |    s    |  d |
--      +--------+---------+----+
select count(*) from dblp18, dblp22, dblp24, dblp1, dblp12, dblp3, dblp5 where dblp18.s = dblp22.s and dblp22.d = dblp24.d and dblp24.s = dblp1.s and dblp1.d = dblp12.d and dblp12.s = dblp3.s and dblp3.d = dblp5.s;
\set queryname dblp_acyclic_211_03
-- Result size: 18358053
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp3 [label="dblp3|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp1:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp25:s;dblp25:d -> dblp12:d;dblp12:s -> dblp3:s;dblp3:d -> dblp9:s;}
--                             +-------+----+----+
--                             | dblp1 |  s |  d |
--                             +-------+----+----+
--                                        |
--                                        |
--                                        |
--                             +-------+----+----+
--                             | dblp5 |  s |  d | ------+
--                             +-------+----+----+       |
--                   +--------+--------+----+            |
--                   | dblp12 |    s   |  d | ------+    |
--                   +--------+--------+----+       |    |
--                               |                  |    |
--                               |                  |    |
--                               |                  |    |
-- +-------+----+---+---------+--------+----+       |    |
-- | dblp9 |  s | d |  dblp3  |    s   |  d |       |    |
-- +-------+----+---+---------+--------+----+       |    |
--            |                           |         |    |
--            +---------------------------+         |    |
--                                                  |    |
--                   +--------+--------+----+       |    |
--                   | dblp21 |    s   |  d | ------+----+
--                   +--------+--------+----+       |
--                               |                  |
--                               |                  |
--                               |                  |
--                   +--------+--------+----+       |
--                   | dblp25 |    s   |  d | ------+
--                   +--------+--------+----+
select count(*) from dblp1, dblp5, dblp21, dblp25, dblp12, dblp3, dblp9 where dblp1.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp25.s and dblp25.d = dblp12.d and dblp12.s = dblp3.s and dblp3.d = dblp9.s;
--\set queryname dblp_acyclic_211_04
-- Result size: 1857024538
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp11 [label="dblp11|<s> s|<d> d"]; dblp23:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp9:s;dblp9:d -> dblp11:s;}
--             +--------------------------------------+
--             |                                      |
--             |            +-------+----+----+       |
--             |            | dblp1 |  s |  d | -+    |
--             |            +-------+----+----+  |    |
--             |                       |         |    |
--             |                       |         |    |
--             |                       |         |    |
-- +--------+----+---------+--------+----+----+  |    |
-- | dblp11 |  s |    d    |  dblp9 |  s |  d | -+----+
-- +--------+----+---------+--------+----+----+  |
--                                               |
--                                          +----+
--                                          |
--                +--------+--------+----+  |
--                | dblp21 |    s   |  d | -+----+
--                +--------+--------+----+  |    |
--                            |             |    |
--                            |             |    |
--                            |             |    |
--                +--------+--------+----+  |    |
--                | dblp25 |    s   |  d | -+    |
--                +--------+--------+----+       |
--                +--------+--------+----+       |
--                | dblp23 |    s   |  d |       |
--                +--------+--------+----+       |
--                            |                  |
--                            |                  |
--                            |                  |
--                +--------+--------+----+       |
--                | dblp5  |    s   |  d | ------+
--                +--------+--------+----+
--select count(*) from dblp23, dblp5, dblp21, dblp25, dblp1, dblp9, dblp11 where dblp23.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp9.s and dblp9.d = dblp11.s;
--\set queryname dblp_acyclic_211_05
-- Result size: 118258051925
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp16:s;dblp16:d -> dblp17:d;dblp17:s -> dblp14:s;dblp14:d -> dblp21:s;}
--                          +--------+----+----+
--                          | dblp2  |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--                          +--------+----+----+
--                          | dblp1  |  s |  d |
--                          +--------+----+----+
--                                           |
--                                           |
--                                           |
--                          +--------+----+----+
--                          | dblp25 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--      +--------+---------+---------+  |
--      | dblp14 |    s    |    d    |  |
--      +--------+---------+---------+  |
--                  |         |         |
--   +--------------+         |         +----+
--   |                        |              |
--   |            +--------+---------+----+  |
--   |            | dblp21 |    s    |  d |  |
--   |            +--------+---------+----+  |
--   |                                       |
--   |              +------------------------+
--   |              |
--   |  +--------+---------+---------+
--   |  | dblp16 |    s    |    d    |
--   |  +--------+---------+---------+
--   |                        |
--   +--------------+         |
--                  |         |
--      +--------+---------+---------+
--      | dblp17 |    s    |    d    |
--      +--------+---------+---------+
--select count(*) from dblp2, dblp1, dblp25, dblp16, dblp17, dblp14, dblp21 where dblp2.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp16.s and dblp16.d = dblp17.d and dblp17.s = dblp14.s and dblp14.d = dblp21.s;
\set queryname dblp_acyclic_211_06
-- Result size: 376871501
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp8:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp2:s;dblp2:d -> dblp24:s;}
--                     +--------+----+----+
--                     | dblp8  |  s |  d |
--                     +--------+----+----+
--                                 |
--                                 |
--                                 |
--                     +--------+----+----+
--                     | dblp25 |  s |  d |
--                     +--------+----+----+
--                                      |
--                                      |
--                                      |
--                     +--------+----+----+
--                     | dblp1  |  s |  d |
--                     +--------+----+----+
--                                 |
--                                 |
--                                 |
--                     +--------+----+----+
--                     | dblp5  |  s |  d |
--                     +--------+----+----+
--                                      |
--                                      |
--                                      |
-- +--------+---------+---------+       |
-- | dblp2  |    s    |    d    |       |
-- +--------+---------+---------+       |
--             |         |              |
--   +---------+         |              |
--   |                   |              |
--   |       +--------+---------+----+  |
--   |       | dblp24 |    s    |  d |  |
--   |       +--------+---------+----+  |
--   |                                  |
--   +---------+                        |
--             |                        |
-- +--------+---------+---------+       |
-- | dblp21 |    s    |    d    | ------+
-- +--------+---------+---------+
select count(*) from dblp8, dblp25, dblp1, dblp5, dblp21, dblp2, dblp24 where dblp8.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp2.s and dblp2.d = dblp24.s;
--\set queryname dblp_acyclic_211_07
-- Result size: 64440516429
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp5:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp16:s;dblp16:d -> dblp17:d;dblp17:s -> dblp14:s;dblp14:d -> dblp22:s;}
--                          +--------+----+----+
--                          | dblp5  |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--                          +--------+----+----+
--                          | dblp1  |  s |  d |
--                          +--------+----+----+
--                                           |
--                                           |
--                                           |
--                          +--------+----+----+
--                          | dblp25 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--      +--------+---------+---------+  |
--      | dblp14 |    s    |    d    |  |
--      +--------+---------+---------+  |
--                  |         |         |
--   +--------------+         |         +----+
--   |                        |              |
--   |            +--------+---------+----+  |
--   |            | dblp22 |    s    |  d |  |
--   |            +--------+---------+----+  |
--   |                                       |
--   |              +------------------------+
--   |              |
--   |  +--------+---------+---------+
--   |  | dblp16 |    s    |    d    |
--   |  +--------+---------+---------+
--   |                        |
--   +--------------+         |
--                  |         |
--      +--------+---------+---------+
--      | dblp17 |    s    |    d    |
--      +--------+---------+---------+
--select count(*) from dblp5, dblp1, dblp25, dblp16, dblp17, dblp14, dblp22 where dblp5.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp16.s and dblp16.d = dblp17.d and dblp17.s = dblp14.s and dblp14.d = dblp22.s;
--\set queryname dblp_acyclic_211_08
-- Result size: 73923496801
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp7:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp16:s;dblp16:d -> dblp17:d;dblp17:s -> dblp2:s;dblp2:d -> dblp21:s;}
--                     +--------+----+----+
--                     | dblp7  |  s |  d |
--                     +--------+----+----+
--                                 |
--                                 |
--                                 |
--                     +--------+----+----+
--                     | dblp1  |  s |  d |
--                     +--------+----+----+
--                                      |
--                                      |
--                                      |
--                     +--------+----+----+
--                     | dblp25 |  s |  d |
--                     +--------+----+----+
--                                 |
--             +-------------------+
--             |
-- +--------+---------+---------+
-- | dblp16 |    s    |    d    |
-- +--------+---------+---------+
--                       |
--                       |
--                       |
-- +--------+---------+---------+
-- | dblp17 |    s    |    d    |
-- +--------+---------+---------+
--             |
--             |
--             |
-- +--------+---------+---------+
-- | dblp2  |    s    |    d    |
-- +--------+---------+---------+
--                       |
--                       |
--                       |
--           +--------+---------+----+
--           | dblp21 |    s    |  d |
--           +--------+---------+----+
--select count(*) from dblp7, dblp1, dblp25, dblp16, dblp17, dblp2, dblp21 where dblp7.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp16.s and dblp16.d = dblp17.d and dblp17.s = dblp2.s and dblp2.d = dblp21.s;
--\set queryname dblp_acyclic_211_09
-- Result size: 4014233652487
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp24:s -> dblp16:s;dblp16:d -> dblp19:d;dblp19:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp17:s;dblp17:d -> dblp2:s;}
--                                            +--------+----+----+
--                                            | dblp1  |  s |  d |
--                                            +--------+----+----+
--                                                        |    |
--                      +---------------------------------+    |
--                      |                                      |
--                      |                     +--------+----+----+
--                      |                     | dblp25 |  s |  d |
--                      |                     +--------+----+----+
--                      |                                 |
--             +--------+--------------+                  |
--             |        |              |                  |
-- +--------+----+---+  |  +--------+--------+---------+  |
-- | dblp24 |  s | d |  |  | dblp16 |    s   |    d    |  |
-- +--------+----+---+  |  +--------+--------+---------+  |
--                      |                       |         |
--                      +--------------+        |         |
--                                     |        |         |
--                         +--------+--------+---------+  |
--                         | dblp19 |    s   |    d    |  |
--                         +--------+--------+---------+  |
--                                                        |
--                                     +------------------+
--                                     |
--                         +--------+--------+---------+
--                         | dblp17 |    s   |    d    |
--                         +--------+--------+---------+
--                                              |
--                                              |
--                                              |
--                                   +-------+---------+----+
--                                   | dblp2 |    s    |  d |
--                                   +-------+---------+----+
--select count(*) from dblp24, dblp16, dblp19, dblp1, dblp25, dblp17, dblp2 where dblp24.s = dblp16.s and dblp16.d = dblp19.d and dblp19.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp17.s and dblp17.d = dblp2.s;
\set queryname dblp_acyclic_211_10
-- Result size: 413473941
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp22:s -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp25:s;dblp25:d -> dblp12:d;dblp12:s -> dblp1:s;dblp1:d -> dblp20:s;}
--                     +--------+--------+----+
--                     | dblp25 |    s   |  d |
--                     +--------+--------+----+
--                                 |        |
--   +-----------------------------+        |
--   |                                      |
--   |                 +--------+--------+----+
--   |                 | dblp12 |    s   |  d |
--   |                 +--------+--------+----+
--   |                             |
--   |                             |
--   |                             |
--   |                 +--------+--------+----+
--   |                 | dblp1  |    s   |  d |
--   |                 +--------+--------+----+
--   |                                      |
--   |                                      |
--   |                                      |
--   |  +--------+----+---------+--------+----+---+
--   |  | dblp22 |  s |    d    | dblp20 |  s | d |
--   |  +--------+----+---------+--------+----+---+
--   |              |
--   |              |
--   |              |
--   |  +--------+----+---------+
--   |  | dblp21 |  s |    d    |
--   |  +--------+----+---------+
--   |                   |
--   +--------------+    |
--                  |    |
--      +--------+----+---------+
--      | dblp5  |  s |    d    |
--      +--------+----+---------+
select count(*) from dblp22, dblp21, dblp5, dblp25, dblp12, dblp1, dblp20 where dblp22.s = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp25.s and dblp25.d = dblp12.d and dblp12.s = dblp1.s and dblp1.d = dblp20.s;
--\set queryname dblp_acyclic_211_11
-- Result size: 2145046887
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp18:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp17:s;dblp17:d -> dblp23:s;}
--                          +--------+----+----+
--                          | dblp18 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--                          +--------+----+----+
--                          | dblp1  |  s |  d |
--                          +--------+----+----+
--                                           |
--                                           |
--                                           |
--                          +--------+----+----+
--                          | dblp25 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--      +--------+---------+---------+  |
--      | dblp17 |    s    |    d    |  |
--      +--------+---------+---------+  |
--                  |         |         |
--   +--------------+         |         +----+
--   |                        |              |
--   |            +--------+---------+----+  |
--   |            | dblp23 |    s    |  d |  |
--   |            +--------+---------+----+  |
--   |                                       |
--   |              +------------------------+
--   |              |
--   |  +--------+---------+---------+
--   |  | dblp21 |    s    |    d    |
--   |  +--------+---------+---------+
--   |                        |
--   +--------------+         |
--                  |         |
--      +--------+---------+---------+
--      | dblp5  |    s    |    d    |
--      +--------+---------+---------+
--select count(*) from dblp18, dblp1, dblp25, dblp21, dblp5, dblp17, dblp23 where dblp18.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp17.s and dblp17.d = dblp23.s;
\set queryname dblp_acyclic_211_12
-- Result size: 315092313
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp5:s -> dblp1:s;dblp1:d -> dblp12:d;dblp12:s -> dblp19:s;dblp19:d -> dblp17:d;dblp17:s -> dblp18:s;dblp18:d -> dblp22:s;}
--           +--------+----+----+
--           | dblp5  |  s |  d |
--           +--------+----+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp1  |  s |  d |
--           +--------+----+----+
--                            |
--                            |
--                            |
--           +--------+----+----+
--           | dblp12 |  s |  d |
--           +--------+----+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp19 |  s |  d |
--           +--------+----+----+
--                            |
--                            |
--                            |
-- +--------+---------+----+  |
-- | dblp17 |    s    |  d | -+
-- +--------+---------+----+
--             |
--             |
--             |
-- +--------+---------+----+
-- | dblp18 |    s    |  d |
-- +--------+---------+----+
--                       |
--                       |
--                       |
--           +--------+----+----+
--           | dblp22 |  s |  d |
--           +--------+----+----+
select count(*) from dblp5, dblp1, dblp12, dblp19, dblp17, dblp18, dblp22 where dblp5.s = dblp1.s and dblp1.d = dblp12.d and dblp12.s = dblp19.s and dblp19.d = dblp17.d and dblp17.s = dblp18.s and dblp18.d = dblp22.s;
--\set queryname dblp_acyclic_211_13
-- Result size: 2944954638
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp2:s -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp19:s;dblp19:d -> dblp22:s;}
--                +--------+---------+----+
--                | dblp25 |    s    |  d |
--                +--------+---------+----+
--                            |         |
--   +------------------------+         |
--   |                                  |
--   |            +--------+---------+----+
--   |            | dblp1  |    s    |  d |
--   |            +--------+---------+----+
--   |                        |
--   |                        |
--   |                        |
--   |            +--------+---------+----+
--   |            | dblp19 |    s    |  d |
--   |            +--------+---------+----+
--   |                                  |
--   |                                  |
--   |                                  |
--   |                      +--------+----+---+
--   |                      | dblp22 |  s | d |
--   |                      +--------+----+---+
--   |  +--------+---------+---------+
--   |  | dblp2  |    s    |    d    |
--   |  +--------+---------+---------+
--   |              |
--   |              |
--   |              |
--   |  +--------+---------+---------+
--   |  | dblp21 |    s    |    d    |
--   |  +--------+---------+---------+
--   |                        |
--   +--------------+         |
--                  |         |
--      +--------+---------+---------+
--      | dblp5  |    s    |    d    |
--      +--------+---------+---------+
--select count(*) from dblp2, dblp21, dblp5, dblp25, dblp1, dblp19, dblp22 where dblp2.s = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp19.s and dblp19.d = dblp22.s;
--\set queryname dblp_acyclic_211_14
-- Result size: 8004209043
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp16:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp19:s;dblp19:d -> dblp17:d;dblp17:s -> dblp8:s;dblp8:d -> dblp7:s;}
--                             +--------+----+----+
--                             | dblp16 |  s |  d |
--                             +--------+----+----+
--                                         |
--                                         |
--                                         |
--                             +--------+----+----+
--                             | dblp5  |  s |  d | ------+
--                             +--------+----+----+       |
--                   +--------+---------+----+            |
--                   | dblp17 |    s    |  d | ------+    |
--                   +--------+---------+----+       |    |
--                               |                   |    |
--                               |                   |    |
--                               |                   |    |
-- +-------+----+---+---------+---------+----+       |    |
-- | dblp7 |  s | d |  dblp8  |    s    |  d |       |    |
-- +-------+----+---+---------+---------+----+       |    |
--            |                            |         |    |
--            +----------------------------+         |    |
--                                                   |    |
--                   +--------+---------+----+       |    |
--                   | dblp19 |    s    |  d | ------+    |
--                   +--------+---------+----+            |
--                               |                        |
--                               |                        |
--                               |                        |
--                   +--------+---------+----+            |
--                   | dblp21 |    s    |  d | -----------+
--                   +--------+---------+----+
--select count(*) from dblp16, dblp5, dblp21, dblp19, dblp17, dblp8, dblp7 where dblp16.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp19.s and dblp19.d = dblp17.d and dblp17.s = dblp8.s and dblp8.d = dblp7.s;
--\set queryname dblp_acyclic_211_15
-- Result size: 23590212305
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp2:s -> dblp16:s;dblp16:d -> dblp17:d;dblp17:s -> dblp25:s;dblp25:d -> dblp12:d;dblp12:s -> dblp1:s;dblp1:d -> dblp26:s;}
--                +--------+--------+----+
--                | dblp12 |    s   |  d | ------+
--                +--------+--------+----+       |
--                            |                  |
--                            |                  |
--                            |                  |
--                +--------+--------+----+       |
--                | dblp1  |    s   |  d |       |
--                +--------+--------+----+       |
--                                     |         |
--                                     |         |
--                                     |         |
-- +--------+----+---------+--------+----+----+  |
-- | dblp2  |  s |    d    | dblp26 |  s |  d |  |
-- +--------+----+---------+--------+----+----+  |
--             |                                 |
--             |                                 |
--             |                                 |
-- +--------+----+---------+                     |
-- | dblp16 |  s |    d    |                     |
-- +--------+----+---------+                     |
--                  |                            |
--                  |                            |
--                  |                            |
-- +--------+----+---------+                     |
-- | dblp17 |  s |    d    |                     |
-- +--------+----+---------+                     |
--             |                                 |
--             |                                 |
--             |                                 |
-- +--------+----+---------+                     |
-- | dblp25 |  s |    d    | --------------------+
-- +--------+----+---------+
--select count(*) from dblp2, dblp16, dblp17, dblp25, dblp12, dblp1, dblp26 where dblp2.s = dblp16.s and dblp16.d = dblp17.d and dblp17.s = dblp25.s and dblp25.d = dblp12.d and dblp12.s = dblp1.s and dblp1.d = dblp26.s;
--\set queryname dblp_acyclic_211_16
-- Result size: 821103225900
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp20:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp19:s;dblp19:d -> dblp16:d;dblp16:s -> dblp21:s;dblp21:d -> dblp18:s;}
--                +--------+----+----+
--                | dblp20 |  s |  d |
--                +--------+----+----+
--                            |
--                            |
--                            |
--                +--------+----+----+
--                | dblp1  |  s |  d |
--                +--------+----+----+
--                                 |
--                                 |
--                                 |
--                +--------+----+----+
--                | dblp25 |  s |  d |
--                +--------+----+----+
--      +--------+---------+----+
--      | dblp16 |    s    |  d | ------+
--      +--------+---------+----+       |
--                  |                   |
--                  |                   |
--                  |                   |
--      +--------+---------+----+       |
--      | dblp21 |    s    |  d |       |
--      +--------+---------+----+       |
--                            |         |
--   +------------------------+         |
--   |                                  |
--   |  +--------+---------+----+       |
--   |  | dblp19 |    s    |  d | ------+
--   |  +--------+---------+----+
--   |
--   +------------------------+
--                            |
--                +--------+----+----+
--                | dblp18 |  s |  d |
--                +--------+----+----+
--select count(*) from dblp20, dblp1, dblp25, dblp19, dblp16, dblp21, dblp18 where dblp20.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp19.s and dblp19.d = dblp16.d and dblp16.s = dblp21.s and dblp21.d = dblp18.s;
\set queryname dblp_acyclic_211_17
-- Result size: 813011
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp5:s -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp1:s;dblp1:d -> dblp12:d;dblp12:s -> dblp21:s;dblp21:d -> dblp17:s;}
-- +--------+---------+----+
-- | dblp5  |    s    |  d |
-- +--------+---------+----+
--             |
--             |
--             |
-- +--------+---------+----+
-- | dblp24 |    s    |  d |
-- +--------+---------+----+
--                       |
--                       |
--                       |
-- +--------+---------+----+
-- | dblp22 |    s    |  d |
-- +--------+---------+----+
--             |
--             |
--             |
-- +--------+---------+----+
-- | dblp1  |    s    |  d |
-- +--------+---------+----+
--                       |
--                       |
--                       |
-- +--------+---------+----+
-- | dblp12 |    s    |  d |
-- +--------+---------+----+
--             |
--             |
--             |
-- +--------+---------+----+
-- | dblp21 |    s    |  d |
-- +--------+---------+----+
--                       |
--                       |
--                       |
--           +--------+----+---+
--           | dblp17 |  s | d |
--           +--------+----+---+
select count(*) from dblp5, dblp24, dblp22, dblp1, dblp12, dblp21, dblp17 where dblp5.s = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp1.s and dblp1.d = dblp12.d and dblp12.s = dblp21.s and dblp21.d = dblp17.s;
\set queryname dblp_acyclic_211_18
-- Result size: 20486991
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp3 [label="dblp3|<s> s|<d> d"]; dblp8:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp16:s;dblp16:d -> dblp3:s;}
--                    +--------+----+----+
--                    | dblp8  |  s |  d |
--                    +--------+----+----+
--                                |
--                                |
--                                |
--                    +--------+----+----+
--                    | dblp25 |  s |  d |
--                    +--------+----+----+
--                                     |
--                                     |
--                                     |
--                    +--------+----+----+
--                    | dblp1  |  s |  d |
--                    +--------+----+----+
--                                |
--                                |
--                                |
--                    +--------+----+----+
--                    | dblp24 |  s |  d |
--                    +--------+----+----+
--                                     |
--                                     |
--                                     |
-- +--------+--------+---------+       |
-- | dblp16 |    s   |    d    |       |
-- +--------+--------+---------+       |
--             |        |              |
--   +---------+        |              |
--   |                  |              |
--   |       +-------+---------+----+  |
--   |       | dblp3 |    s    |  d |  |
--   |       +-------+---------+----+  |
--   |                                 |
--   +---------+                       |
--             |                       |
-- +--------+--------+---------+       |
-- | dblp22 |    s   |    d    | ------+
-- +--------+--------+---------+
select count(*) from dblp8, dblp25, dblp1, dblp24, dblp22, dblp16, dblp3 where dblp8.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp16.s and dblp16.d = dblp3.s;
\set queryname dblp_acyclic_211_19
-- Result size: 439553913
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp20:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp2:s;dblp2:d -> dblp7:s;}
--                  +-----------------------------------------------+
--                  |                                               |
--                  |                     +-------+----+----+       |
--                  |                     | dblp1 |  s |  d | -+    |
--                  |                     +-------+----+----+  |    |
--                  |                                |         |    |
--                  |                                |         |    |
--                  |                                |         |    |
--                  |                     +-------+----+----+  |    |
--                  |                     | dblp5 |  s |  d | -+----+
--                  |                     +-------+----+----+  |
--                  |                                          |
--                  |                                     +----+
--                  |                                     |
-- +--------+----+----++-------+---------+--------+       |
-- | dblp21 |  s |  d || dblp2 |    s    |    d   |       |
-- +--------+----+----++-------+---------+--------+       |
--             |                  |         |             |
--             +------------------+         |             |
--                                          |             |
--                              +--------+--------+----+  |
--                              | dblp7  |    s   |  d |  |
--                              +--------+--------+----+  |
--                              +--------+--------+----+  |
--                              | dblp20 |    s   |  d |  |
--                              +--------+--------+----+  |
--                                          |             |
--                                          |             |
--                                          |             |
--                              +--------+--------+----+  |
--                              | dblp25 |    s   |  d | -+
--                              +--------+--------+----+
select count(*) from dblp20, dblp25, dblp1, dblp5, dblp21, dblp2, dblp7 where dblp20.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp2.s and dblp2.d = dblp7.s;
