--\set queryname dblp_acyclic_217_00
-- Result size: 275221093936
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp26:d -> dblp9:s;dblp9:d -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp16:s;dblp16:d -> dblp19:d;dblp19:s -> dblp24:s;dblp24:s -> dblp21:s;}
--                                        +--------+----+----+
--                                        | dblp25 |  s |  d |
--                                        +--------+----+----+
--                                                    |    |
--             +--------------------------------------+    |
--             |                                           |
--             |                          +--------+----+----+
--             |                          | dblp1  |  s |  d |
--             |                          +--------+----+----+
--             |
--             |        +-----------------------------+
--             |        |                             |
-- +--------+----+---+  |       +--------+---------+----+
-- | dblp16 |  s | d | -+       | dblp19 |    s    |  d |
-- +--------+----+---+          +--------+---------+----+
--                                          |
--                                          |
--                                          |
--                              +--------+---------+----+
--                              | dblp24 |    s    |  d |
--                              +--------+---------+----+
--                                          |
--                                          |
--                                          |
--                              +--------+---------+----+
--                              | dblp21 |    s    |  d |
--                              +--------+---------+----+
--                    +--------+---------+---------+
--                    | dblp26 |    s    |    d    |
--                    +--------+---------+---------+
--                                          |
--                                          |
--                                          |
--                              +--------+---------+----+
--                              | dblp9  |    s    |  d |
--                              +--------+---------+----+
--select count(*) from dblp26, dblp9, dblp1, dblp25, dblp16, dblp19, dblp24, dblp21 where dblp26.d = dblp9.s and dblp9.d = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp16.s and dblp16.d = dblp19.d and dblp19.s = dblp24.s and dblp24.s = dblp21.s;
\set queryname dblp_acyclic_217_01
-- Result size: 104303
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp9:d -> dblp8:s;dblp8:d -> dblp25:s;dblp25:d -> dblp12:d;dblp12:s -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp19:s;dblp19:s -> dblp21:s;}
--                                                +--------+----+----+
--                                                | dblp24 |  s |  d |
--                                                +--------+----+----+
--                                                            |    |
--                                                            |    +----+
--                                                            |         |
--                   +--------+----+---+          +--------+----+----+  |
--                   | dblp25 |  s | d | -+       | dblp12 |  s |  d |  |
--                   +--------+----+---+  |       +--------+----+----+  |
--                               |        |                        |    |
--                               |        +------------------------+    |
--                               |                                      |
--          +-------+---------+----+    +--------+---------+----+       |
--          | dblp8 |    s    |  d |    | dblp22 |    s    |  d | ------+
--          +-------+---------+----+    +--------+---------+----+
--                     |                            |
--                     |                            |
--                     |                            |
-- +-------+--------+---------+         +--------+---------+----+
-- | dblp9 |    s   |    d    |         | dblp19 |    s    |  d |
-- +-------+--------+---------+         +--------+---------+----+
--                                                  |
--                                                  |
--                                                  |
--                                      +--------+---------+----+
--                                      | dblp21 |    s    |  d |
--                                      +--------+---------+----+
select count(*) from dblp9, dblp8, dblp25, dblp12, dblp24, dblp22, dblp19, dblp21 where dblp9.d = dblp8.s and dblp8.d = dblp25.s and dblp25.d = dblp12.d and dblp12.s = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp19.s and dblp19.s = dblp21.s;
\set queryname dblp_acyclic_217_02
-- Result size: 1605250
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp19:d -> dblp8:s;dblp8:d -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp9:s;dblp9:s -> dblp20:s;}
--                +--------+----+----+-------+----+----+
--                | dblp19 |  s |  d | dblp8 |  s |  d |
--                +--------+----+----+-------+----+----+
--                                 |            |    |
--   +------------------------+    +------------+    |
--   |                        |                      |
--   |  +--------+---------+----+                    |
--   |  | dblp21 |    s    |  d |                    |
--   |  +--------+---------+----+                    |
--   |              |                                |
--   |              |                                |
--   |              |                                |
--   |  +--------+---------+----+                    |
--   |  | dblp9  |    s    |  d |                    |
--   |  +--------+---------+----+                    |
--   |              |                                |
--   |              |                                |
--   |              |                                |
--   |  +--------+---------+----+                    |
--   |  | dblp20 |    s    |  d |                    |
--   |  +--------+---------+----+                    |
--   |  +--------+---------+----+                    |
--   |  | dblp22 |    s    |  d | ------+            |
--   |  +--------+---------+----+       |            |
--   |              |                   |            |
--   |              |                   |            |
--   |              |                   |            |
--   |  +--------+---------+----+       |            |
--   |  | dblp5  |    s    |  d |       |            |
--   |  +--------+---------+----+       |            |
--   |                        |         |            |
--   +------------------------+         |            |
--                                      |            |
--      +--------+---------+----+       |            |
--      | dblp24 |    s    |  d | ------+            |
--      +--------+---------+----+                    |
--                  |                                |
--                  +--------------------------------+
select count(*) from dblp19, dblp8, dblp24, dblp22, dblp5, dblp21, dblp9, dblp20 where dblp19.d = dblp8.s and dblp8.d = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp9.s and dblp9.s = dblp20.s;
\set queryname dblp_acyclic_217_03
-- Result size: 477922668
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp17:d -> dblp9:s;dblp9:d -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp12:s;dblp12:d -> dblp1:d;dblp1:s -> dblp24:s;dblp24:s -> dblp6:s;}
--                    +--------+----+----+
--                    | dblp5  |  s |  d |
--                    +--------+----+----+
--                                |    |
--             +------------------+    |
--             |                       |
--             |      +--------+----+----+
--             |      | dblp21 |  s |  d |
--             |      +--------+----+----+
--             |                  |
--             |                  |
--             |                  |
--             |      +--------+----+----+
--             |      | dblp12 |  s |  d |
--             |      +--------+----+----+
--             |                       |
--             |                       |
--             |                       |
--             |      +--------+----+----+
--             |      | dblp1  |  s |  d |
--             |      +--------+----+----+
--             |                  |
--             |                  |
--             |                  |
--             |      +--------+----+----+
--             |      | dblp24 |  s |  d |
--             |      +--------+----+----+
--             |                  |
--             |                  |
--             |                  |
--             |      +--------+----+----+
--             |      | dblp6  |  s |  d |
--             |      +--------+----+----+
--             |
--             +------------------+
--                                |
-- +--------+--------+---------+  |
-- | dblp17 |    s   |    d    |  |
-- +--------+--------+---------+  |
--                      |         |
--                      |         |
--                      |         |
--           +-------+---------+----+
--           | dblp9 |    s    |  d |
--           +-------+---------+----+
select count(*) from dblp17, dblp9, dblp5, dblp21, dblp12, dblp1, dblp24, dblp6 where dblp17.d = dblp9.s and dblp9.d = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp12.s and dblp12.d = dblp1.d and dblp1.s = dblp24.s and dblp24.s = dblp6.s;
\set queryname dblp_acyclic_217_04
-- Result size: 447402451
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp9:d -> dblp2:s;dblp2:d -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp16:s;dblp16:d -> dblp17:d;dblp17:s -> dblp19:s;dblp19:s -> dblp14:s;}
--                                    +-----------------------------+
--                                    |                             |
--                                    |       +--------+----+----+  |
--                  +-----------------+       | dblp14 |  s |  d |  |
--                  |                         +--------+----+----+  |
--                  |                                     |         |
--                  |                                     +----+    |
--                  |                                          |    |
-- +--------+----+--------+         +--------+---------+----+  |    |
-- | dblp16 |  s |    d   |         | dblp17 |    s    |  d |  |    |
-- +--------+----+--------+         +--------+---------+----+  |    |
--             |                                |         |    |    |
--             |                                |         +----+----+
--             |                                |              |
-- +--------+----+--------+         +--------+---------+----+  |
-- | dblp22 |  s |    d   |         | dblp19 |    s    |  d |  |
-- +--------+----+--------+         +--------+---------+----+  |
--                  |                           |              |
--                  |                           +--------------+
--                  |
--                  |
--                  +-------------------------------------+
--                                                        |
--                         +-------+---------+---------+  |
--                         | dblp2 |    s    |    d    |  |
--                         +-------+---------+---------+  |
--                                    |         |         |
--                           +--------+         |         |
--                           |                  |         |
--                           |      +--------+---------+----+
--                           |      | dblp24 |    s    |  d |
--                           |      +--------+---------+----+
--                           |
--                           +--------+
--                                    |
--                +-------+--------+---------+
--                | dblp9 |    s   |    d    |
--                +-------+--------+---------+
select count(*) from dblp9, dblp2, dblp24, dblp22, dblp16, dblp17, dblp19, dblp14 where dblp9.d = dblp2.s and dblp2.d = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp16.s and dblp16.d = dblp17.d and dblp17.s = dblp19.s and dblp19.s = dblp14.s;
\set queryname dblp_acyclic_217_05
-- Result size: 6230386
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1:d -> dblp26:s;dblp26:d -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp2:s;dblp2:s -> dblp25:s;}
--           +-------+---+----+--------+----+----+-------+----+----+
--           | dblp1 | s |  d | dblp26 |  s |  d | dblp5 |  s |  d |
--           +-------+---+----+--------+----+----+-------+----+----+
--                          |             |    |            |    |
--                          +-------------+    +------------+    |
--                                                               |
-- +--------+--------+---+                                       |
-- | dblp22 |    s   | d | ------+                               |
-- +--------+--------+---+       |                               |
--             |                 |                               |
--             |                 |                               |
--             |                 |                               |
-- +--------+--------+---+       |                               |
-- | dblp2  |    s   | d |       |                               |
-- +--------+--------+---+       |                               |
--             |                 |                               |
--             |                 |                               |
--             |                 |                               |
-- +--------+--------+---+       |                               |
-- | dblp25 |    s   | d |       |                               |
-- +--------+--------+---+       |                               |
-- +--------+--------+---+       |                               |
-- | dblp21 |    s   | d | ------+-------------------------------+
-- +--------+--------+---+       |
--             |                 |
--             |                 |
--             |                 |
-- +--------+--------+---+       |
-- | dblp24 |    s   | d | ------+
-- +--------+--------+---+
select count(*) from dblp1, dblp26, dblp5, dblp21, dblp24, dblp22, dblp2, dblp25 where dblp1.d = dblp26.s and dblp26.d = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp2.s and dblp2.s = dblp25.s;
\set queryname dblp_acyclic_217_06
-- Result size: 812283965
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp17:d -> dblp2:s;dblp2:d -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp23:s;dblp23:s -> dblp7:s;}
--                     +--------+----+----+
--                     | dblp21 |  s |  d | -+
--                     +--------+----+----+  |
--                                 |         |
--                                 |         |
--                                 |         |
--                     +--------+----+----+  |
--                     | dblp1  |  s |  d |  |
--                     +--------+----+----+  |
--                                      |    |
--                                      |    |
--                                      |    |
--           +--------+---------+----+  |    |
--           | dblp25 |    s    |  d | -+    |
--           +--------+---------+----+       |
--                       |                   |
--                       |              +----+
--                       |              |
--           +--------+---------+----+  |
--           | dblp23 |    s    |  d |  |
--           +--------+---------+----+  |
--                       |              |
--                       |              |
--                       |              |
--           +--------+---------+----+  |
--           | dblp7  |    s    |  d |  |
--           +--------+---------+----+  |
-- +--------+---------+---------+       |
-- | dblp17 |    s    |    d    |       |
-- +--------+---------+---------+       |
--                       |              |
--                       |              |
--                       |              |
--           +--------+---------+----+  |
--           | dblp2  |    s    |  d |  |
--           +--------+---------+----+  |
--                                 |    |
--                                 |    |
--                                 |    |
--                     +--------+----+----+
--                     | dblp5  |  s |  d |
--                     +--------+----+----+
select count(*) from dblp17, dblp2, dblp5, dblp21, dblp1, dblp25, dblp23, dblp7 where dblp17.d = dblp2.s and dblp2.d = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp23.s and dblp23.s = dblp7.s;
--\set queryname dblp_acyclic_217_07
-- Result size: 88385212240
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp21:d -> dblp2:s;dblp2:d -> dblp19:s;dblp19:d -> dblp17:d;dblp17:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp22:s;dblp22:s -> dblp8:s;}
--             +---------------------------------+
--             |                                 |
--             |                +--------+----+----+
--             |                | dblp1  |  s |  d |
--             |                +--------+----+----+
--             |                            |
--             |                            |
--             |                            |
--             |                +--------+----+----+
--             |                | dblp22 |  s |  d |
--             |                +--------+----+----+
--             |                            |
--             |                            |
--             |                            |
--             |                +--------+----+----+
--             |                | dblp8  |  s |  d |
--             |                +--------+----+----+
--             |      +--------+---------+----+
--             |      | dblp17 |    s    |  d | ------+
--             |      +--------+---------+----+       |
--             |                  |                   |
--             |                  |                   |
--             |                  |                   |
--             |      +--------+---------+----+       |
--             |      | dblp25 |    s    |  d |       |
--             |      +--------+---------+----+       |
--             |                            |         |
--             +----------------------------+         |
--                                                    |
--                    +--------+---------+----+       |
--                    | dblp19 |    s    |  d | ------+
--                    +--------+---------+----+
--                                |
--                                |
--                                |
--           +-------+---------+---------+
--           | dblp2 |    s    |    d    |
--           +-------+---------+---------+
--                      |
--                      |
--                      |
-- +--------+--------+---------+
-- | dblp21 |    s   |    d    |
-- +--------+--------+---------+
--select count(*) from dblp21, dblp2, dblp19, dblp17, dblp25, dblp1, dblp22, dblp8 where dblp21.d = dblp2.s and dblp2.d = dblp19.s and dblp19.d = dblp17.d and dblp17.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp22.s and dblp22.s = dblp8.s;
\set queryname dblp_acyclic_217_08
-- Result size: 79539608
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp21:d -> dblp2:s;dblp2:d -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp9:s;dblp9:s -> dblp20:s;}
--             +---------------------------------+
--             |                                 |
--             |                +--------+----+----+
--             |                | dblp22 |  s |  d |
--             |                +--------+----+----+
--             |                            |
--             |                            |
--             |                            |
--             |                +--------+----+----+
--             |                | dblp1  |  s |  d |
--             |                +--------+----+----+
--             |                                 |
--             |                                 |
--             |                                 |
--             |      +--------+---------+----+  |
--             |      | dblp25 |    s    |  d | -+
--             |      +--------+---------+----+
--             |                  |
--             |                  |
--             |                  |
--             |      +--------+---------+----+
--             |      | dblp9  |    s    |  d |
--             |      +--------+---------+----+
--             |                  |
--             |                  |
--             |                  |
--             |      +--------+---------+----+
--             |      | dblp20 |    s    |  d |
--             |      +--------+---------+----+
--             |
--             +----------------------------+
--                                          |
--           +-------+---------+---------+  |
--           | dblp2 |    s    |    d    |  |
--           +-------+---------+---------+  |
--                      |         |         |
--             +--------+         |         |
--             |                  |         |
--             |      +--------+---------+----+
--             |      | dblp24 |    s    |  d |
--             |      +--------+---------+----+
--             |
--             +--------+
--                      |
-- +--------+--------+---------+
-- | dblp21 |    s   |    d    |
-- +--------+--------+---------+
select count(*) from dblp21, dblp2, dblp24, dblp22, dblp1, dblp25, dblp9, dblp20 where dblp21.d = dblp2.s and dblp2.d = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp9.s and dblp9.s = dblp20.s;
\set queryname dblp_acyclic_217_09
-- Result size: 282183
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp26 [label="dblp26|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp13 [label="dblp13|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp7 [label="dblp7|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp26:d -> dblp17:s;dblp17:d -> dblp13:s;dblp13:d -> dblp2:d;dblp2:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp7:s;dblp7:s -> dblp16:s;}
--                                         +-------+----+----+
--                                         | dblp1 |  s |  d |
--                                         +-------+----+----+
--                                                    |    |
--             +--------------------------------------+    |
--             |                                           |
--             |                 +--------+--------+----+  |
--             |                 | dblp25 |    s   |  d | -+
--             |                 +--------+--------+----+
--             |                             |
--             |                             |
--             |                             |
--             |                 +--------+--------+----+
--             |                 | dblp7  |    s   |  d |
--             |                 +--------+--------+----+
--             |                             |
--             |                             |
--             |                             |
--             |                 +--------+--------+----+
--             |                 | dblp16 |    s   |  d |
--             |                 +--------+--------+----+
--             |
--             |                   +------------------+
--             |                   |                  |
--             |       +--------+---------+--------+  |
--             |       | dblp13 |    s    |    d   |  |
--             |       +--------+---------+--------+  |
--             |                             |        |
--             +-------------------+         |        |
--                                 |         |        |
--                     +--------+---------+--------+  |
--                     | dblp2  |    s    |    d   |  |
--                     +--------+---------+--------+  |
--           +--------+---------+---------+           |
--           | dblp17 |    s    |    d    | ----------+
--           +--------+---------+---------+
--                       |
--                       |
--                       |
-- +--------+---------+---------+
-- | dblp26 |    s    |    d    |
-- +--------+---------+---------+
select count(*) from dblp26, dblp17, dblp13, dblp2, dblp1, dblp25, dblp7, dblp16 where dblp26.d = dblp17.s and dblp17.d = dblp13.s and dblp13.d = dblp2.d and dblp2.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp7.s and dblp7.s = dblp16.s;
\set queryname dblp_acyclic_217_10
-- Result size: 444122
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp11 [label="dblp11|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp19:d -> dblp9:s;dblp9:d -> dblp24:s;dblp24:d -> dblp22:d;dblp22:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp11:s;dblp11:s -> dblp20:s;}
--                          +--------+----+----+
--                          | dblp20 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--                          +--------+----+----+
--                          | dblp11 |  s |  d |
--                          +--------+----+----+
--                                      |
--                                      |
--                                      |
--                          +--------+----+----+
--                          | dblp21 |  s |  d |
--                          +--------+----+----+
--                                           |
--   +----------------------------------+    |
--   |                                  |    |
--   |  +--------+---------+---------+  |    |
--   |  | dblp19 |    s    |    d    |  |    |
--   |  +--------+---------+---------+  |    |
--   |                        |         |    |
--   |                        |         |    |
--   |                        |         |    |
--   |            +--------+---------+----+  |
--   |            | dblp9  |    s    |  d |  |
--   |            +--------+---------+----+  |
--   |                                       |
--   |    +----------------------------------+
--   |    |
--   |    |       +--------+---------+----+
--   |    |       | dblp22 |    s    |  d | ------+
--   |    |       +--------+---------+----+       |
--   |    |                   |                   |
--   |    |                   |                   |
--   |    |                   |                   |
--   |    |       +--------+---------+----+       |
--   |    |       | dblp5  |    s    |  d |       |
--   |    |       +--------+---------+----+       |
--   |    |                             |         |
--   |    +-----------------------------+         |
--   |                                            |
--   |            +--------+---------+----+       |
--   |            | dblp24 |    s    |  d | ------+
--   |            +--------+---------+----+
--   |                        |
--   +------------------------+
select count(*) from dblp19, dblp9, dblp24, dblp22, dblp5, dblp21, dblp11, dblp20 where dblp19.d = dblp9.s and dblp9.d = dblp24.s and dblp24.d = dblp22.d and dblp22.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp11.s and dblp11.s = dblp20.s;
\set queryname dblp_acyclic_217_11
-- Result size: 674892
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp14 [label="dblp14|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp12 [label="dblp12|<s> s|<d> d"]; dblp13 [label="dblp13|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp14:d -> dblp21:s;dblp21:d -> dblp1:s;dblp1:d -> dblp12:d;dblp12:s -> dblp13:s;dblp13:d -> dblp2:d;dblp2:s -> dblp5:s;dblp5:s -> dblp20:s;}
--                     +--------+----+----+
--                     | dblp13 |  s |  d |
--                     +--------+----+----+
--                                 |    |
--                                 |    +----+
--                                 |         |
--                     +--------+----+----+  |
--                     | dblp12 |  s |  d |  |
--                     +--------+----+----+  |
--                                      |    |
--   +-----------------------------+    |    |
--   |                             |    |    |
--   |                 +--------+----+----+  |
--   |                 | dblp1  |  s |  d |  |
--   |                 +--------+----+----+  |
--   |       +--------+---------+----+       |
--   |       | dblp2  |    s    |  d | ------+
--   |       +--------+---------+----+
--   |                   |
--   |                   |
--   |                   |
--   |       +--------+---------+----+
--   |       | dblp5  |    s    |  d |
--   |       +--------+---------+----+
--   |                   |
--   |                   |
--   |                   |
--   |       +--------+---------+----+
--   |       | dblp20 |    s    |  d |
--   |       +--------+---------+----+
--   |
--   +-----------------------------+
--                                 |
-- +--------+---------+---------+  |
-- | dblp14 |    s    |    d    |  |
-- +--------+---------+---------+  |
--                       |         |
--                       |         |
--                       |         |
--           +--------+---------+----+
--           | dblp21 |    s    |  d |
--           +--------+---------+----+
select count(*) from dblp14, dblp21, dblp1, dblp12, dblp13, dblp2, dblp5, dblp20 where dblp14.d = dblp21.s and dblp21.d = dblp1.s and dblp1.d = dblp12.d and dblp12.s = dblp13.s and dblp13.d = dblp2.d and dblp2.s = dblp5.s and dblp5.s = dblp20.s;
\set queryname dblp_acyclic_217_12
-- Result size: 139822504
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp17:d -> dblp8:s;dblp8:d -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp18:s;dblp18:s -> dblp6:s;}
--                         +--------+----+----+
--                         | dblp25 |  s |  d |
--                         +--------+----+----+
--                                     |    |
--   +---------------------------------+    |
--   |                                      |
--   |                     +--------+----+----+
--   |                     | dblp1  |  s |  d |
--   |                     +--------+----+----+
--   |                                 |
--   |                                 |
--   |                                 |
--   |                     +--------+----+----+
--   |                     | dblp18 |  s |  d |
--   |                     +--------+----+----+
--   |                                 |
--   |                                 |
--   |                                 |
--   |                     +--------+----+----+
--   |                     | dblp6  |  s |  d |
--   |                     +--------+----+----+
--   |  +--------+--------+---------+
--   |  | dblp17 |    s   |    d    |
--   |  +--------+--------+---------+
--   |                       |
--   |                       |
--   |                       |
--   |            +-------+---------+----+
--   |            | dblp8 |    s    |  d |
--   |            +-------+---------+----+
--   |                                 |
--   |              +------------------+
--   |              |
--   |  +--------+--------+---------+
--   |  | dblp21 |    s   |    d    |
--   |  +--------+--------+---------+
--   |                       |
--   +--------------+        |
--                  |        |
--      +--------+--------+---------+
--      | dblp5  |    s   |    d    |
--      +--------+--------+---------+
select count(*) from dblp17, dblp8, dblp21, dblp5, dblp25, dblp1, dblp18, dblp6 where dblp17.d = dblp8.s and dblp8.d = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp18.s and dblp18.s = dblp6.s;
--\set queryname dblp_acyclic_217_13
-- Result size: 1228946411958
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp16 [label="dblp16|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp18:d -> dblp5:s;dblp5:d -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp19:s;dblp19:d -> dblp16:d;dblp16:s -> dblp23:s;dblp23:s -> dblp17:s;}
--                                    +--------+----+----+
--                                    | dblp19 |  s |  d |
--                                    +--------+----+----+
--                                                |    |
--                                                |    +----+
--                                                |         |
-- +--------+----+---------+          +--------+----+----+  |
-- | dblp25 |  s |    d    | -+       | dblp1  |  s |  d |  |
-- +--------+----+---------+  |       +--------+----+----+  |
--             |              |                        |    |
--             |              +------------------------+    |
--             |                                            |
--             |            +--------+---------+----+       |
--             |            | dblp16 |    s    |  d | ------+
--             |            +--------+---------+----+
--             |                        |
--             |                        |
--             |                        |
--             |            +--------+---------+----+
--             |            | dblp23 |    s    |  d |
--             |            +--------+---------+----+
--             |                        |
--             |                        |
--             |                        |
--             |            +--------+---------+----+
--             |            | dblp17 |    s    |  d |
--             |            +--------+---------+----+
--             |
--             +----------------------------------+
--                                                |
--                +--------+---------+---------+  |
--                | dblp18 |    s    |    d    |  |
--                +--------+---------+---------+  |
--                                      |         |
--                                      |         |
--                                      |         |
--                          +--------+---------+----+
--                          | dblp5  |    s    |  d |
--                          +--------+---------+----+
--select count(*) from dblp18, dblp5, dblp25, dblp1, dblp19, dblp16, dblp23, dblp17 where dblp18.d = dblp5.s and dblp5.d = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp19.s and dblp19.d = dblp16.d and dblp16.s = dblp23.s and dblp23.s = dblp17.s;
--\set queryname dblp_acyclic_217_14
-- Result size: 4955017850
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp19 [label="dblp19|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp18 [label="dblp18|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp8:d -> dblp5:s;dblp5:d -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp19:s;dblp19:d -> dblp17:d;dblp17:s -> dblp18:s;dblp18:s -> dblp9:s;}
--                                   +--------+----+-------+
--                                   | dblp25 |  s |   d   |
--                                   +--------+----+-------+
--                                               |    |
--             +---------------------------------+    |
--             |                                      |
--             |                     +--------+----+-------+-------+----+---+
--             |                     | dblp1  |  s |   d   | dblp5 |  s | d |
--             |                     +--------+----+-------+-------+----+---+
--             |                                                      |
--             |        +------------------------+                    |
--             |        |                        |                    |
-- +--------+----+---+  |  +--------+---------+----+-------+-------+----+
-- | dblp19 |  s | d | -+  | dblp17 |    s    |  d | dblp8 |   s   |  d |
-- +--------+----+---+     +--------+---------+----+-------+-------+----+
--                                     |
--                                     |
--                                     |
--                         +--------+---------+----+
--                         | dblp18 |    s    |  d |
--                         +--------+---------+----+
--                                     |
--                                     |
--                                     |
--                         +--------+---------+----+
--                         | dblp9  |    s    |  d |
--                         +--------+---------+----+
--select count(*) from dblp8, dblp5, dblp1, dblp25, dblp19, dblp17, dblp18, dblp9 where dblp8.d = dblp5.s and dblp5.d = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp19.s and dblp19.d = dblp17.d and dblp17.s = dblp18.s and dblp18.s = dblp9.s;
\set queryname dblp_acyclic_217_15
-- Result size: 78657
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp13 [label="dblp13|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp27 [label="dblp27|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp17:d -> dblp9:s;dblp9:d -> dblp2:s;dblp2:d -> dblp13:d;dblp13:s -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp27:s;dblp27:s -> dblp23:s;}
--                                   +--------+----+----+
--                                   | dblp21 |  s |  d |
--                                   +--------+----+----+
--                                               |    |
--                                               |    +----+
--                                               |         |
-- +-------+----+---------+          +--------+----+----+  |
-- | dblp2 |  s |    d    | -+       | dblp13 |  s |  d |  |
-- +-------+----+---------+  |       +--------+----+----+  |
--            |              |                        |    |
--            |              +------------------------+    |
--            |                                            |
--            |            +--------+---------+----+       |
--            |            | dblp5  |    s    |  d | ------+
--            |            +--------+---------+----+
--            |                        |
--            |                        |
--            |                        |
--            |            +--------+---------+----+
--            |            | dblp27 |    s    |  d |
--            |            +--------+---------+----+
--            |                        |
--            |                        |
--            |                        |
--            |            +--------+---------+----+
--            |            | dblp23 |    s    |  d |
--            |            +--------+---------+----+
--            |
--            +----------------------------------+
--                                               |
--               +--------+---------+---------+  |
--               | dblp17 |    s    |    d    |  |
--               +--------+---------+---------+  |
--                                     |         |
--                                     |         |
--                                     |         |
--                         +--------+---------+----+
--                         | dblp9  |    s    |  d |
--                         +--------+---------+----+
select count(*) from dblp17, dblp9, dblp2, dblp13, dblp21, dblp5, dblp27, dblp23 where dblp17.d = dblp9.s and dblp9.d = dblp2.s and dblp2.d = dblp13.d and dblp13.s = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp27.s and dblp27.s = dblp23.s;
--\set queryname dblp_acyclic_217_16
-- Result size: 3559413184
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp20 [label="dblp20|<s> s|<d> d"]; dblp2:d -> dblp17:s;dblp17:d -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp23:s;dblp23:s -> dblp20:s;}
--                                                        +-------------------+
--                                                        |                   |
--                                            +--------+----+----+            |
--                                            | dblp25 |  s |  d |            |
--                                            +--------+----+----+            |
--                                                             |              |
--                                                             |              |
--                                                             |              |
--          +--------+----+---+               +--------+----+----+            |
--          | dblp17 |  s | d | ------+       | dblp1  |  s |  d |            |
--          +--------+----+---+       |       +--------+----+----+            |
--                      |             |                   |                   |
--                      |             +-------------------+                   |
--                      |                                                     |
-- +-------+---------+----+         +--------+---------+----+     +--------+----+----+
-- | dblp2 |    s    |  d |         | dblp5  |    s    |  d |     | dblp21 |  s |  d |
-- +-------+---------+----+         +--------+---------+----+     +--------+----+----+
--                                              |         |                        |
--                                              |         +------------------------+
--                                              |
--                                  +--------+---------+----+
--                                  | dblp23 |    s    |  d |
--                                  +--------+---------+----+
--                                              |
--                                              |
--                                              |
--                                  +--------+---------+----+
--                                  | dblp20 |    s    |  d |
--                                  +--------+---------+----+
--select count(*) from dblp2, dblp17, dblp1, dblp25, dblp21, dblp5, dblp23, dblp20 where dblp2.d = dblp17.s and dblp17.d = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp23.s and dblp23.s = dblp20.s;
\set queryname dblp_acyclic_217_17
-- Result size: 491171783
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp8 [label="dblp8|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp22 [label="dblp22|<s> s|<d> d"]; dblp8:d -> dblp2:s;dblp2:d -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp17:s;dblp17:s -> dblp22:s;}
--            +---------------------------------+
--            |                                 |
--            |                +--------+----+----+
--            |                | dblp21 |  s |  d |
--            |                +--------+----+----+
--            |                            |
--            |                            |
--            |                            |
--            |                +--------+----+----+
--            |                | dblp1  |  s |  d |
--            |                +--------+----+----+
--            |                                 |
--            |                                 |
--            |                                 |
--            |      +--------+---------+----+  |
--            |      | dblp25 |    s    |  d | -+
--            |      +--------+---------+----+
--            |                  |
--            |                  |
--            |                  |
--            |      +--------+---------+----+
--            |      | dblp17 |    s    |  d |
--            |      +--------+---------+----+
--            |                  |
--            |                  |
--            |                  |
--            |      +--------+---------+----+
--            |      | dblp22 |    s    |  d |
--            |      +--------+---------+----+
--            |
--            +----------------------------+
--                                         |
--          +-------+---------+---------+  |
--          | dblp2 |    s    |    d    |  |
--          +-------+---------+---------+  |
--                     |         |         |
--            +--------+         |         |
--            |                  |         |
--            |      +--------+---------+----+
--            |      | dblp5  |    s    |  d |
--            |      +--------+---------+----+
--            |
--            +--------+
--                     |
-- +-------+--------+---------+
-- | dblp8 |    s   |    d    |
-- +-------+--------+---------+
select count(*) from dblp8, dblp2, dblp5, dblp21, dblp1, dblp25, dblp17, dblp22 where dblp8.d = dblp2.s and dblp2.d = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp17.s and dblp17.s = dblp22.s;
--\set queryname dblp_acyclic_217_18
-- Result size: 4094798636
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp23 [label="dblp23|<s> s|<d> d"]; dblp6 [label="dblp6|<s> s|<d> d"]; dblp17:d -> dblp2:s;dblp2:d -> dblp1:s;dblp1:d -> dblp25:d;dblp25:s -> dblp5:s;dblp5:d -> dblp21:d;dblp21:s -> dblp23:s;dblp23:s -> dblp6:s;}
--                     +--------+----+----+
--                     | dblp5  |  s |  d |
--                     +--------+----+----+
--                                 |    |
--                                 |    +----+
--                                 |         |
--                     +--------+----+----+  |
--                     | dblp25 |  s |  d |  |
--                     +--------+----+----+  |
--                                      |    |
--                                      |    |
--                                      |    |
--                     +--------+----+----+  |
--                     | dblp1  |  s |  d |  |
--                     +--------+----+----+  |
--                                 |         |
--                                 +----+    |
--                                      |    |
--           +--------+---------+----+  |    |
--           | dblp21 |    s    |  d |  |    |
--           +--------+---------+----+  |    |
--                       |         |    |    |
--                       |         +----+----+
--                       |              |
--           +--------+---------+----+  |
--           | dblp23 |    s    |  d |  |
--           +--------+---------+----+  |
--                       |              |
--                       |              |
--                       |              |
--           +--------+---------+----+  |
--           | dblp6  |    s    |  d |  |
--           +--------+---------+----+  |
--                                      |
--                                 +----+
--                                 |
-- +--------+---------+---------+  |
-- | dblp17 |    s    |    d    |  |
-- +--------+---------+---------+  |
--                       |         |
--                       |         |
--                       |         |
--           +--------+---------+----+
--           | dblp2  |    s    |  d |
--           +--------+---------+----+
--select count(*) from dblp17, dblp2, dblp1, dblp25, dblp5, dblp21, dblp23, dblp6 where dblp17.d = dblp2.s and dblp2.d = dblp1.s and dblp1.d = dblp25.d and dblp25.s = dblp5.s and dblp5.d = dblp21.d and dblp21.s = dblp23.s and dblp23.s = dblp6.s;
--\set queryname dblp_acyclic_217_19
-- Result size: 1582366189
-- digraph G { node [shape=record]; edge [arrowhead=none]; dblp9 [label="dblp9|<s> s|<d> d"]; dblp2 [label="dblp2|<s> s|<d> d"]; dblp21 [label="dblp21|<s> s|<d> d"]; dblp5 [label="dblp5|<s> s|<d> d"]; dblp25 [label="dblp25|<s> s|<d> d"]; dblp1 [label="dblp1|<s> s|<d> d"]; dblp24 [label="dblp24|<s> s|<d> d"]; dblp17 [label="dblp17|<s> s|<d> d"]; dblp9:d -> dblp2:s;dblp2:d -> dblp21:s;dblp21:d -> dblp5:d;dblp5:s -> dblp25:s;dblp25:d -> dblp1:d;dblp1:s -> dblp24:s;dblp24:s -> dblp17:s;}
--                                                           +---------+
--                                                           |         |
--                                               +--------+----+----+  |
--                                               | dblp25 |  s |  d |  |
--                                               +--------+----+----+  |
--                                                                |    |
--                                                                |    |
--                                                                |    |
--                                               +--------+----+----+  |
--                                               | dblp1  |  s |  d |  |
--                                               +--------+----+----+  |
--                                                           |         |
--                                                           |         |
--                                                           |         |
--                                               +--------+----+----+  |
--                                               | dblp24 |  s |  d |  |
--                                               +--------+----+----+  |
--                                                           |         |
--                                                           |         |
--                                                           |         |
--                                               +--------+----+----+  |
--                                               | dblp17 |  s |  d |  |
--                                               +--------+----+----+  |
-- +-------+---+---+          +-------+---------+---------+            |
-- | dblp9 | s | d | ------+  | dblp2 |    s    |    d    |            |
-- +-------+---+---+       |  +-------+---------+---------+            |
--                         |             |         |                   |
--                         +-------------+         |                   |
--                                                 |                   |
--                                     +--------+---------+----+       |
--                                     | dblp21 |    s    |  d |       |
--                                     +--------+---------+----+       |
--                                                           |         |
--                                                           |         |
--                                                           |         |
--                                     +--------+---------+----+       |
--                                     | dblp5  |    s    |  d |       |
--                                     +--------+---------+----+       |
--                                                 |                   |
--                                                 +-------------------+
--select count(*) from dblp9, dblp2, dblp21, dblp5, dblp25, dblp1, dblp24, dblp17 where dblp9.d = dblp2.s and dblp2.d = dblp21.s and dblp21.d = dblp5.d and dblp5.s = dblp25.s and dblp25.d = dblp1.d and dblp1.s = dblp24.s and dblp24.s = dblp17.s;
