--\set queryname hetio_acyclic_208_00
-- Result size: 23927215463112
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45181:s -> hetio45178:s;hetio45178:s -> hetio45165:s;hetio45165:s -> hetio45167:s;hetio45167:d -> hetio45177:s;hetio45177:d -> hetio45160:s;hetio45160:s -> hetio45174:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45177 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45174 |  s | d |              | hetio45160 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45165 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45181, hetio45178, hetio45165, hetio45167, hetio45177, hetio45160, hetio45174 where hetio45181.s = hetio45178.s and hetio45178.s = hetio45165.s and hetio45165.s = hetio45167.s and hetio45167.d = hetio45177.s and hetio45177.d = hetio45160.s and hetio45160.s = hetio45174.s;
--\set queryname hetio_acyclic_208_01
-- Result size: 302438407722411
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45178:s -> hetio45166:s;hetio45166:s -> hetio45181:s;hetio45181:s -> hetio45167:s;hetio45167:d -> hetio45177:s;hetio45177:d -> hetio45159:s;hetio45159:s -> hetio45174:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45177 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45174 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45178, hetio45166, hetio45181, hetio45167, hetio45177, hetio45159, hetio45174 where hetio45178.s = hetio45166.s and hetio45166.s = hetio45181.s and hetio45181.s = hetio45167.s and hetio45167.d = hetio45177.s and hetio45177.d = hetio45159.s and hetio45159.s = hetio45174.s;
--\set queryname hetio_acyclic_208_02
-- Result size: 6494892123938
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45168 [label="hetio45168|<s> s|<d> d"]; hetio45163 [label="hetio45163|<s> s|<d> d"]; hetio45169 [label="hetio45169|<s> s|<d> d"]; hetio45164 [label="hetio45164|<s> s|<d> d"]; hetio45182 [label="hetio45182|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45176 [label="hetio45176|<s> s|<d> d"]; hetio45168:s -> hetio45163:s;hetio45163:s -> hetio45169:s;hetio45169:s -> hetio45164:s;hetio45164:d -> hetio45182:s;hetio45182:d -> hetio45180:s;hetio45180:s -> hetio45176:s;}
--                 +--------------------------------+
--                 |                                |
--                 |           +------------+----+----+
--                 |           | hetio45164 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45169 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45163 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45168 |  s |  d |
--                 |           +------------+----+----+
--                 |
--                 |
--                 |
-- +------------+-------------+-------------+
-- | hetio45182 |      s      |      d      |
-- +------------+-------------+-------------+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45180 |      s      |  d |
--               +------------+-------------+----+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45176 |      s      |  d |
--               +------------+-------------+----+
--select count(*) from hetio45168, hetio45163, hetio45169, hetio45164, hetio45182, hetio45180, hetio45176 where hetio45168.s = hetio45163.s and hetio45163.s = hetio45169.s and hetio45169.s = hetio45164.s and hetio45164.d = hetio45182.s and hetio45182.d = hetio45180.s and hetio45180.s = hetio45176.s;
--\set queryname hetio_acyclic_208_03
-- Result size: 5038788650200
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45181:s -> hetio45161:s;hetio45161:s -> hetio45166:s;hetio45166:s -> hetio45178:s;hetio45178:d -> hetio45177:s;hetio45177:d -> hetio45160:s;hetio45160:s -> hetio45180:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45177 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45180 |  s | d |              | hetio45160 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45181, hetio45161, hetio45166, hetio45178, hetio45177, hetio45160, hetio45180 where hetio45181.s = hetio45161.s and hetio45161.s = hetio45166.s and hetio45166.s = hetio45178.s and hetio45178.d = hetio45177.s and hetio45177.d = hetio45160.s and hetio45160.s = hetio45180.s;
--\set queryname hetio_acyclic_208_04
-- Result size: 8988577589540
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45161:s -> hetio45167:s;hetio45167:s -> hetio45178:s;hetio45178:s -> hetio45166:s;hetio45166:d -> hetio45160:s;hetio45160:d -> hetio45159:s;hetio45159:s -> hetio45180:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45160 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45180 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45161, hetio45167, hetio45178, hetio45166, hetio45160, hetio45159, hetio45180 where hetio45161.s = hetio45167.s and hetio45167.s = hetio45178.s and hetio45178.s = hetio45166.s and hetio45166.d = hetio45160.s and hetio45160.d = hetio45159.s and hetio45159.s = hetio45180.s;
--\set queryname hetio_acyclic_208_05
-- Result size: 747936837148
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45170 [label="hetio45170|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45176 [label="hetio45176|<s> s|<d> d"]; hetio45170:s -> hetio45181:s;hetio45181:s -> hetio45178:s;hetio45178:s -> hetio45167:s;hetio45167:d -> hetio45177:s;hetio45177:d -> hetio45180:s;hetio45180:s -> hetio45176:s;}
--                             +------------+----+----+
--                             | hetio45167 |  s |  d | -+
--                             +------------+----+----+  |
--                                             |         |
--                                             +----+    |
--                                                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45170 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               |                  |    |
--                               |                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45181 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               |                  |    |
--                               |                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45178 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               +------------------+    |
--                                                       |
--                                                       |
--                 +-------------------------------------+
--                 |
-- +------------+-------------+-------------+
-- | hetio45177 |      s      |      d      |
-- +------------+-------------+-------------+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45180 |      s      |  d |
--               +------------+-------------+----+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45176 |      s      |  d |
--               +------------+-------------+----+
--select count(*) from hetio45170, hetio45181, hetio45178, hetio45167, hetio45177, hetio45180, hetio45176 where hetio45170.s = hetio45181.s and hetio45181.s = hetio45178.s and hetio45178.s = hetio45167.s and hetio45167.d = hetio45177.s and hetio45177.d = hetio45180.s and hetio45180.s = hetio45176.s;
--\set queryname hetio_acyclic_208_06
-- Result size: 10929396757895
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45170 [label="hetio45170|<s> s|<d> d"]; hetio45169 [label="hetio45169|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45181:s -> hetio45178:s;hetio45178:s -> hetio45161:s;hetio45161:s -> hetio45170:s;hetio45170:d -> hetio45169:s;hetio45169:d -> hetio45159:s;hetio45159:s -> hetio45180:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45169 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45180 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45170 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45181, hetio45178, hetio45161, hetio45170, hetio45169, hetio45159, hetio45180 where hetio45181.s = hetio45178.s and hetio45178.s = hetio45161.s and hetio45161.s = hetio45170.s and hetio45170.d = hetio45169.s and hetio45169.d = hetio45159.s and hetio45159.s = hetio45180.s;
--\set queryname hetio_acyclic_208_07
-- Result size: 3591806251684
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45176 [label="hetio45176|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45173 [label="hetio45173|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45180:s -> hetio45160:s;hetio45160:s -> hetio45176:s;hetio45176:s -> hetio45177:s;hetio45177:d -> hetio45173:s;hetio45173:d -> hetio45174:s;hetio45174:s -> hetio45159:s;}
--                             +------------+----+----+
--                             | hetio45159 |  s |  d |
--                             +------------+----+----+
--                                             |
--                                             +----+
--                                                  |
--               +------------+-------------+----+  |
--               | hetio45180 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45160 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45176 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45177 |      s      |  d |  |
--               +------------+-------------+----+  |
--                                             |    |
--                 +---------------------------+    |
--                 |                                |
-- +------------+-------------+-------------+       |
-- | hetio45173 |      s      |      d      |       |
-- +------------+-------------+-------------+       |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45174 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               +------------------+
--select count(*) from hetio45180, hetio45160, hetio45176, hetio45177, hetio45173, hetio45174, hetio45159 where hetio45180.s = hetio45160.s and hetio45160.s = hetio45176.s and hetio45176.s = hetio45177.s and hetio45177.d = hetio45173.s and hetio45173.d = hetio45174.s and hetio45174.s = hetio45159.s;
--\set queryname hetio_acyclic_208_08
-- Result size: 1104526206973
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45176 [label="hetio45176|<s> s|<d> d"]; hetio45173 [label="hetio45173|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45180:s -> hetio45159:s;hetio45159:s -> hetio45176:s;hetio45176:s -> hetio45173:s;hetio45173:d -> hetio45177:s;hetio45177:d -> hetio45174:s;hetio45174:s -> hetio45160:s;}
--                 +--------------------------------+
--                 |                                |
--                 |           +------------+----+----+
--                 |           | hetio45173 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45176 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45159 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45180 |  s |  d |
--                 |           +------------+----+----+
--                 |
--                 |
--                 |
-- +------------+-------------+-------------+
-- | hetio45177 |      s      |      d      |
-- +------------+-------------+-------------+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45174 |      s      |  d |
--               +------------+-------------+----+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45160 |      s      |  d |
--               +------------+-------------+----+
--select count(*) from hetio45180, hetio45159, hetio45176, hetio45173, hetio45177, hetio45174, hetio45160 where hetio45180.s = hetio45159.s and hetio45159.s = hetio45176.s and hetio45176.s = hetio45173.s and hetio45173.d = hetio45177.s and hetio45177.d = hetio45174.s and hetio45174.s = hetio45160.s;
--\set queryname hetio_acyclic_208_09
-- Result size: 79937081183
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45168 [label="hetio45168|<s> s|<d> d"]; hetio45163 [label="hetio45163|<s> s|<d> d"]; hetio45169 [label="hetio45169|<s> s|<d> d"]; hetio45166:s -> hetio45161:s;hetio45161:s -> hetio45181:s;hetio45181:s -> hetio45165:s;hetio45165:d -> hetio45168:s;hetio45168:d -> hetio45163:s;hetio45163:s -> hetio45169:s;}
--                 +--------------------------------+
--                 |                                |
--                 |           +------------+----+----+
--                 |           | hetio45165 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45181 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45161 |  s |  d |
--                 |           +------------+----+----+
--                 |                           |
--                 |                           |
--                 |                           |
--                 |           +------------+----+----+
--                 |           | hetio45166 |  s |  d |
--                 |           +------------+----+----+
--                 |
--                 |
--                 |
-- +------------+-------------+-------------+
-- | hetio45168 |      s      |      d      |
-- +------------+-------------+-------------+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45163 |      s      |  d |
--               +------------+-------------+----+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45169 |      s      |  d |
--               +------------+-------------+----+
--select count(*) from hetio45166, hetio45161, hetio45181, hetio45165, hetio45168, hetio45163, hetio45169 where hetio45166.s = hetio45161.s and hetio45161.s = hetio45181.s and hetio45181.s = hetio45165.s and hetio45165.d = hetio45168.s and hetio45168.d = hetio45163.s and hetio45163.s = hetio45169.s;
--\set queryname hetio_acyclic_208_10
-- Result size: 1143724431199
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45168 [label="hetio45168|<s> s|<d> d"]; hetio45163 [label="hetio45163|<s> s|<d> d"]; hetio45164 [label="hetio45164|<s> s|<d> d"]; hetio45178:s -> hetio45181:s;hetio45181:s -> hetio45166:s;hetio45166:s -> hetio45165:s;hetio45165:d -> hetio45168:s;hetio45168:d -> hetio45163:s;hetio45163:s -> hetio45164:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45168 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45164 |  s | d |              | hetio45163 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45165 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45178, hetio45181, hetio45166, hetio45165, hetio45168, hetio45163, hetio45164 where hetio45178.s = hetio45181.s and hetio45181.s = hetio45166.s and hetio45166.s = hetio45165.s and hetio45165.d = hetio45168.s and hetio45168.d = hetio45163.s and hetio45163.s = hetio45164.s;
--\set queryname hetio_acyclic_208_11
-- Result size: 6472685324226
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45181:s -> hetio45166:s;hetio45166:s -> hetio45161:s;hetio45161:s -> hetio45167:s;hetio45167:d -> hetio45177:s;hetio45177:d -> hetio45159:s;hetio45159:s -> hetio45174:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45177 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45174 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45181, hetio45166, hetio45161, hetio45167, hetio45177, hetio45159, hetio45174 where hetio45181.s = hetio45166.s and hetio45166.s = hetio45161.s and hetio45161.s = hetio45167.s and hetio45167.d = hetio45177.s and hetio45177.d = hetio45159.s and hetio45159.s = hetio45174.s;
--\set queryname hetio_acyclic_208_12
-- Result size: 86998611488
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45170 [label="hetio45170|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45173 [label="hetio45173|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45170:s -> hetio45181:s;hetio45181:s -> hetio45166:s;hetio45166:s -> hetio45178:s;hetio45178:d -> hetio45160:s;hetio45160:d -> hetio45173:s;hetio45173:s -> hetio45159:s;}
--                             +------------+----+----+
--                             | hetio45159 |  s |  d |
--                             +------------+----+----+
--                                             |
--                                             +----+
--                                                  |
--               +------------+-------------+----+  |
--               | hetio45170 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45181 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45166 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45178 |      s      |  d |  |
--               +------------+-------------+----+  |
--                                             |    |
--                 +---------------------------+    |
--                 |                                |
-- +------------+-------------+-------------+       |
-- | hetio45160 |      s      |      d      |       |
-- +------------+-------------+-------------+       |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45173 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               +------------------+
--select count(*) from hetio45170, hetio45181, hetio45166, hetio45178, hetio45160, hetio45173, hetio45159 where hetio45170.s = hetio45181.s and hetio45181.s = hetio45166.s and hetio45166.s = hetio45178.s and hetio45178.d = hetio45160.s and hetio45160.d = hetio45173.s and hetio45173.s = hetio45159.s;
--\set queryname hetio_acyclic_208_13
-- Result size: 116903706884434
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45169 [label="hetio45169|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45178:s -> hetio45167:s;hetio45167:s -> hetio45181:s;hetio45181:s -> hetio45165:s;hetio45165:d -> hetio45169:s;hetio45169:d -> hetio45174:s;hetio45174:s -> hetio45180:s;}
--                             +------------+----+----+
--                             | hetio45165 |  s |  d | -+
--                             +------------+----+----+  |
--                                             |         |
--                                             +----+    |
--                                                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45178 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               |                  |    |
--                               |                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45167 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               |                  |    |
--                               |                  |    |
--               +------------+-------------+----+  |    |
--               | hetio45181 |      s      |  d |  |    |
--               +------------+-------------+----+  |    |
--                               |                  |    |
--                               +------------------+    |
--                                                       |
--                                                       |
--                 +-------------------------------------+
--                 |
-- +------------+-------------+-------------+
-- | hetio45169 |      s      |      d      |
-- +------------+-------------+-------------+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45174 |      s      |  d |
--               +------------+-------------+----+
--                               |
--                               |
--                               |
--               +------------+-------------+----+
--               | hetio45180 |      s      |  d |
--               +------------+-------------+----+
--select count(*) from hetio45178, hetio45167, hetio45181, hetio45165, hetio45169, hetio45174, hetio45180 where hetio45178.s = hetio45167.s and hetio45167.s = hetio45181.s and hetio45181.s = hetio45165.s and hetio45165.d = hetio45169.s and hetio45169.d = hetio45174.s and hetio45174.s = hetio45180.s;
--\set queryname hetio_acyclic_208_14
-- Result size: 487639903959
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45176 [label="hetio45176|<s> s|<d> d"]; hetio45165:s -> hetio45178:s;hetio45178:s -> hetio45181:s;hetio45181:s -> hetio45161:s;hetio45161:d -> hetio45167:s;hetio45167:d -> hetio45160:s;hetio45160:s -> hetio45176:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45176 |  s | d |              | hetio45160 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45165 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45165, hetio45178, hetio45181, hetio45161, hetio45167, hetio45160, hetio45176 where hetio45165.s = hetio45178.s and hetio45178.s = hetio45181.s and hetio45181.s = hetio45161.s and hetio45161.d = hetio45167.s and hetio45167.d = hetio45160.s and hetio45160.s = hetio45176.s;
--\set queryname hetio_acyclic_208_15
-- Result size: 14494672199101
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45178:s -> hetio45165:s;hetio45165:s -> hetio45181:s;hetio45181:s -> hetio45166:s;hetio45166:d -> hetio45160:s;hetio45160:d -> hetio45180:s;hetio45180:s -> hetio45159:s;}
--                             +------------+----+----+
--                             | hetio45159 |  s |  d |
--                             +------------+----+----+
--                                             |
--                                             +----+
--                                                  |
--               +------------+-------------+----+  |
--               | hetio45178 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45165 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45181 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45166 |      s      |  d |  |
--               +------------+-------------+----+  |
--                                             |    |
--                 +---------------------------+    |
--                 |                                |
-- +------------+-------------+-------------+       |
-- | hetio45160 |      s      |      d      |       |
-- +------------+-------------+-------------+       |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45180 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               +------------------+
--select count(*) from hetio45178, hetio45165, hetio45181, hetio45166, hetio45160, hetio45180, hetio45159 where hetio45178.s = hetio45165.s and hetio45165.s = hetio45181.s and hetio45181.s = hetio45166.s and hetio45166.d = hetio45160.s and hetio45160.d = hetio45180.s and hetio45180.s = hetio45159.s;
--\set queryname hetio_acyclic_208_16
-- Result size: 2417717999442
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45164 [label="hetio45164|<s> s|<d> d"]; hetio45168 [label="hetio45168|<s> s|<d> d"]; hetio45163 [label="hetio45163|<s> s|<d> d"]; hetio45169 [label="hetio45169|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45174 [label="hetio45174|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45164:s -> hetio45168:s;hetio45168:s -> hetio45163:s;hetio45163:s -> hetio45169:s;hetio45169:d -> hetio45160:s;hetio45160:d -> hetio45174:s;hetio45174:s -> hetio45159:s;}
--                             +------------+----+----+
--                             | hetio45159 |  s |  d |
--                             +------------+----+----+
--                                             |
--                                             +----+
--                                                  |
--               +------------+-------------+----+  |
--               | hetio45164 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45168 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45163 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45169 |      s      |  d |  |
--               +------------+-------------+----+  |
--                                             |    |
--                 +---------------------------+    |
--                 |                                |
-- +------------+-------------+-------------+       |
-- | hetio45160 |      s      |      d      |       |
-- +------------+-------------+-------------+       |
--                               |                  |
--                               |                  |
--                               |                  |
--               +------------+-------------+----+  |
--               | hetio45174 |      s      |  d |  |
--               +------------+-------------+----+  |
--                               |                  |
--                               +------------------+
--select count(*) from hetio45164, hetio45168, hetio45163, hetio45169, hetio45160, hetio45174, hetio45159 where hetio45164.s = hetio45168.s and hetio45168.s = hetio45163.s and hetio45163.s = hetio45169.s and hetio45169.d = hetio45160.s and hetio45160.d = hetio45174.s and hetio45174.s = hetio45159.s;
--\set queryname hetio_acyclic_208_17
-- Result size: 20992738363
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45170 [label="hetio45170|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45173 [label="hetio45173|<s> s|<d> d"]; hetio45177 [label="hetio45177|<s> s|<d> d"]; hetio45161:s -> hetio45181:s;hetio45181:s -> hetio45170:s;hetio45170:s -> hetio45167:s;hetio45167:d -> hetio45160:s;hetio45160:d -> hetio45173:s;hetio45173:s -> hetio45177:s;}
--                                                            +---------+
--                                                            |         |
--                    +------------+----+----+-------------+----+----+  |
--                    | hetio45160 |  s |  d |  hetio45173 |  s |  d |  |
--                    +------------+----+----+-------------+----+----+  |
--                                    |    |                  |         |
--   +--------------------------------+    +------------------+         |
--   |                                                                  |
--   |  +------------+-------------+----+     +------------+----+----+  |
--   |  | hetio45161 |      s      |  d |     | hetio45177 |  s |  d |  |
--   |  +------------+-------------+----+     +------------+----+----+  |
--   |                  |                                     |         |
--   |                  |                                     +---------+
--   |                  |
--   |  +------------+-------------+----+
--   |  | hetio45181 |      s      |  d |
--   |  +------------+-------------+----+
--   |                  |
--   |                  |
--   |                  |
--   |  +------------+-------------+----+
--   |  | hetio45170 |      s      |  d |
--   |  +------------+-------------+----+
--   |                  |
--   |                  |
--   |                  |
--   |  +------------+-------------+----+
--   |  | hetio45167 |      s      |  d |
--   |  +------------+-------------+----+
--   |                                |
--   +--------------------------------+
--select count(*) from hetio45161, hetio45181, hetio45170, hetio45167, hetio45160, hetio45173, hetio45177 where hetio45161.s = hetio45181.s and hetio45181.s = hetio45170.s and hetio45170.s = hetio45167.s and hetio45167.d = hetio45160.s and hetio45160.d = hetio45173.s and hetio45173.s = hetio45177.s;
--\set queryname hetio_acyclic_208_18
-- Result size: 3419921877770
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45165 [label="hetio45165|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45161 [label="hetio45161|<s> s|<d> d"]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45181:s -> hetio45165:s;hetio45165:s -> hetio45167:s;hetio45167:s -> hetio45161:s;hetio45161:d -> hetio45178:s;hetio45178:d -> hetio45159:s;hetio45159:s -> hetio45180:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45180 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45165 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45161 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45181, hetio45165, hetio45167, hetio45161, hetio45178, hetio45159, hetio45180 where hetio45181.s = hetio45165.s and hetio45165.s = hetio45167.s and hetio45167.s = hetio45161.s and hetio45161.d = hetio45178.s and hetio45178.d = hetio45159.s and hetio45159.s = hetio45180.s;
--\set queryname hetio_acyclic_208_19
-- Result size: 830210657924747
-- digraph G { node [shape=record]; edge [arrowhead=none]; hetio45178 [label="hetio45178|<s> s|<d> d"]; hetio45167 [label="hetio45167|<s> s|<d> d"]; hetio45181 [label="hetio45181|<s> s|<d> d"]; hetio45166 [label="hetio45166|<s> s|<d> d"]; hetio45160 [label="hetio45160|<s> s|<d> d"]; hetio45159 [label="hetio45159|<s> s|<d> d"]; hetio45180 [label="hetio45180|<s> s|<d> d"]; hetio45178:s -> hetio45167:s;hetio45167:s -> hetio45181:s;hetio45181:s -> hetio45166:s;hetio45166:d -> hetio45160:s;hetio45160:d -> hetio45159:s;hetio45159:s -> hetio45180:s;}
--                                        +-----------------------+
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45160 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                                      |         |
--                                                      |         |
--                                                      |         |
-- +------------+----+---+              +------------+----+----+  |
-- | hetio45180 |  s | d |              | hetio45159 |  s |  d |  |
-- +------------+----+---+              +------------+----+----+  |
--                 |                                    |         |
--                 +------------------------------------+         |
--                                                                |
--                        +------------+-------------+----+       |
--                        | hetio45178 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45167 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45181 |      s      |  d |       |
--                        +------------+-------------+----+       |
--                                        |                       |
--                                        |                       |
--                                        |                       |
--                        +------------+-------------+----+       |
--                        | hetio45166 |      s      |  d | ------+
--                        +------------+-------------+----+
--select count(*) from hetio45178, hetio45167, hetio45181, hetio45166, hetio45160, hetio45159, hetio45180 where hetio45178.s = hetio45167.s and hetio45167.s = hetio45181.s and hetio45181.s = hetio45166.s and hetio45166.d = hetio45160.s and hetio45160.d = hetio45159.s and hetio45159.s = hetio45180.s;
